---
output: 
  html_document:
    keep_md: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "Evol exp Analyses"
```

# Description

This repository contains the code and data used to analyse the evol exp data [here](https://https://github.com/nrode/AnalysisEvolExp2020).

## Contents

The [:open_file_folder: **data**](data/) directory contains the data sets used in the analyses. 

The [:open_file_folder: **R**](R/) directory contains the functions used in the analyses.

The [:open_file_folder: **man**](man/) directory contains the documentation for the functions.
  
The [:open_file_folder: **reports**](reports/) directory contains the `.Rmd` files used to build each part of the analyses and produce the final figures. They also have rendered versions and `html` suitable for reading in a web browser.

### Markdown versions

 - [:clipboard: Analysis_main_text](reports/analysis_main_text.Rmd) : All the analyses that can be found in the main text .

 - [:clipboard: Figure_supplements](reports/figure_supplements.Rmd) : All the analyses that can be found in the supplementary materials .
 
 - [:clipboard: Simullogfitness](reports/simullogfitness.Rmd) : Simulations of log fitness data.
 
 
### HTML versions

 - [:clipboard: Analysis_main_text](reports/analysis_main_text.html) : All the analyses that can be found in the main text .

 - [:clipboard: Figure_supplements](reports/figure_supplements.html) : All the analyses that can be found in the supplementary materials .
 
 - [:clipboard: Simullogfitness](reports/simullogfitness.html) : Simulations of log fitness data.

The [:open_file_folder: **figures**](figures/) directory contains the figures generated during the analyses.

The [:hammer: dev_history.R](dev_history.R) file allow to rebuild our research compendium from scratch for maximum reproducibility.


## How to run it ?

This research compendium has been developed using the statistical programming language R. To work with the compendium, you will need
installed on your computer the [R software](https://cloud.r-project.org/)
itself and optionally [RStudio Desktop](https://rstudio.com/products/rstudio/download/).

You can download the compendium by cloning this [repository](https://https://github.com/nrode/AnalysisEvolExp2020):
  
  - open the `.Rproj` file in RStudio

  - open scripts `.Rmd` in reports folder and run it to produce all the analyses and associated reports.
  
  - launch the [`README.html`](README.html) to be able to explore the contents on your web browser


