---
title: "Simulation of log fitness change"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA
```{r }
## Longitudinal data
data_sum <- loadlongitudinaldata(dataset = "DATA_Adults_G1G29.csv", rm_generation1 = 1,rm_generation2 = 7,rm_generation3 = 29)

## Phenotyping steps
data_G0 <- loadfitnessdata(dataset = "Selection_Phenotypage_G0_G7_G8.csv", generation = "G1")
data_G7 <- loadfitnessdata(dataset = "Selection_Phenotypage_G0_G7_G8.csv", generation = "G7")
data_G29 <- loadfitnessdata(dataset = 
                            "PERFORMANCE_Comptage_adultes_G13G14G15G16G17G18G19G20G21G22G23G24G25G26G27G28G29.csv",
                            generation = "29")
head(data_sum)
head(data_G0)
head(data_G7)
head(data_G29)
dim(data_G29)

#Compute log change
data_logchange <- computelogchange(fitness_dataset_intermediate = data_G7, fitness_dataset_final = data_G29)
#Lines: CE2 and CR2 do not pass Geary's test (the threshold of a standardized mean greater than 3)
data_logchange$Line_type  <- ifelse(data_logchange$Line == "CR2"| data_logchange$Line == "CE2", "solid","dashed")


#Formatting for testing correlation
TEMP_dataG7_CheCran <- formattinglogchange(data_logchange, "7", "Cherry", "Cranberry")
TEMP_dataG7_CranStraw <- formattinglogchange(data_logchange, "7", "Cranberry", "Strawberry")
TEMP_dataG7_StrawChe <- formattinglogchange(data_logchange, "7", "Strawberry", "Cherry")

TEMP_dataG29_CheCran <- formattinglogchange(data_logchange, "29", "Cherry", "Cranberry")
TEMP_dataG29_CranStraw <- formattinglogchange(data_logchange, "29", "Cranberry", "Strawberry")
TEMP_dataG29_StrawChe <- formattinglogchange(data_logchange, "29", "Strawberry", "Cherry")

```

# ADAPTATION
## Analysis
```{r }
######## Models
mod_nul <- lme4::lmer(fitness ~ 1 + (1|Generation), 
            weights = N, data = data_sum)

mod_Fruits <- lme4::lmer(fitness ~ Fruit_s + (1|Generation), 
            weights = N, data = data_sum)

mod_Generation <- lme4::lmer(fitness ~ Generation + (1|Generation), 
            weights = N, data = data_sum)

mod_Step <- lme4::lmer(fitness~ Step + (1|Generation), 
            weights = N, data = data_sum)

mod_Lines <- lme4::lmer(fitness~ Line + (1|Generation), 
            weights = N, data = data_sum)

mod_Generation_Step <- lme4::lmer(fitness~ Step + Generation + (1|Generation),  
            weights = N, data = data_sum)

mod_Generation_Fruits <- lme4::lmer(fitness ~ Generation + Fruit_s + (1|Generation), 
            weights = N, data = data_sum)

mod_Fruits_Step <- lme4::lmer(fitness ~ Step + Fruit_s + (1|Generation), 
            weights = N, data = data_sum)


mod_Generation_Fruits_Step <- lme4::lmer(fitness ~ Generation + Step + Fruit_s + (1|Generation), 
                              weights = N, data = data_sum)


mod_Doubleinteraction <- lme4::lmer(fitness ~ Generation + Step + Fruit_s + 
                              Fruit_s:Generation + 
                              (1|Generation),  
                              weights = N, data = data_sum)

mod_Double_gene <- lme4::lmer(fitness ~ Generation*Fruit_s + 
                              (1|Generation), 
                              weights = N, data = data_sum)

mod_Double <- lme4::lmer(fitness ~ Step*Fruit_s + 
                              (1|Generation), 
                              weights = N, data = data_sum)

mod_Double_Generation <- lme4::lmer(fitness ~ Generation + Step*Fruit_s + 
                              (1|Generation), 
                              weights = N, data = data_sum)

mod_Tripleinteraction <- lme4::lmer(fitness ~ Generation*Step*Fruit_s + 
                              (1|Generation), 
                              weights = N, data = data_sum)

mod_DoublePopulationGeneration <- lme4::lmer(fitness ~ Generation*Line + 
                              (1|Generation), 
                              weights = N, data = data_sum)

# AICC and Loglik
MuMIn::AICc(mod_nul,mod_Fruits,mod_Generation,mod_Step,mod_Lines,mod_Generation_Step,mod_Generation_Fruits,mod_Fruits_Step,mod_Generation_Fruits_Step,mod_Double_gene,mod_Doubleinteraction,mod_Double,mod_Double_Generation,mod_Tripleinteraction,mod_DoublePopulationGeneration)

anova(mod_nul,mod_Fruits,mod_Generation,mod_Step,mod_Lines,mod_Generation_Step,mod_Generation_Fruits,mod_Fruits_Step,mod_Generation_Fruits_Step,mod_Doubleinteraction,mod_Double,mod_Double_Generation,mod_Tripleinteraction,mod_DoublePopulationGeneration,mod_Double_gene)

summary(mod_Fruits_Step)

#Posthoc
mod_Best <- lme4::lmer(fitness ~ Step -1 + Fruit_s + (1|Generation),
                     weights = N, data = data_sum)
emmeans::emmeans(mod_Best, list(pairwise ~ Step:Fruit_s), adjust = "tukey") #
emmeans::emmeans(mod_Best, list(pairwise ~ Fruit_s), adjust = "tukey") #
emmeans::emmeans(mod_Best, list(pairwise ~ Step), adjust = "tukey") #

summary(mod_Best)


# Percent of Increase in fitness
Calcul_increase_fitness <- expand.grid(Step = unique(data_sum$Step),
                                     Fruit_s = unique(data_sum$Fruit_s))

Calcul_increase_fitness$fitness_predicted <- predict(mod_Best, newdata = Calcul_increase_fitness, 
                          re.form= NA, type = "response")

((Calcul_increase_fitness$fitness_predicted[Calcul_increase_fitness$Step=="second_postpool"]-
    Calcul_increase_fitness$fitness_predicted[Calcul_increase_fitness$Step=="first_prepool"])/
  abs(Calcul_increase_fitness$fitness_predicted[Calcul_increase_fitness$Step=="first_prepool"]))*100

Calcul_increase_fitness
```







## Plot 
```{r }
#Position dodge
pd <- ggplot2::position_dodge(0.3) # move them .05 to the left and right

#Extract slope and intercept
dat_predict_allfruits <- expand.grid(Generation =as.numeric(levels(as.factor(data_sum$Generation))),
                                     Fruit_s=unique(data_sum$Fruit_s))
dat_predict_allfruits$Step <- ifelse(dat_predict_allfruits$Generation<= 7, "first_prepool",ifelse(dat_predict_allfruits$Generation>=12, "second_postpool", "pool"))

dat_predict_allfruits$fitness_predicted <- predict(mod_Best, newdata = dat_predict_allfruits, 
                          re.form= NA, type = "response")

#REAL DATA
#Add G1 G6 and G7
TEMP_lineG1 <- c(rep(NA, 2), 1,rep(NA, 5))
TEMP_lineG6 <- c(rep(NA, 2), 6,rep(NA, 5))
TEMP_lineG7 <- c(rep(NA, 2), 7,rep(NA, 5))

TEMP_total <- rbind(data_sum,TEMP_lineG1,TEMP_lineG1,TEMP_lineG1,TEMP_lineG6,TEMP_lineG6,TEMP_lineG6,TEMP_lineG7,TEMP_lineG7,TEMP_lineG7)
TEMP_total$Fruit_s[TEMP_total$Generation == "6"] <- c("Strawberry", "Cranberry", "Cherry")
TEMP_total$Fruit_s[TEMP_total$Generation == "1"] <- c("Strawberry", "Cranberry", "Cherry")
TEMP_total$Fruit_s[TEMP_total$Generation == "7"] <- c("Strawberry", "Cranberry", "Cherry")
tail(TEMP_total)


## Add label 
TEMP_anno <- data.frame(x1 = c(3.5, 3.5, 10, 3.5, 3.5, 10, 3.5, 3.5, 10), 
                        x2 = c(9, 17.5, 17.5, 9, 17.5, 17.5, 9, 17.5, 17.5),
                        y1 = c(1, 2, 1.2, 1, 2, 1.2, 1, 2, 1.2), 
                        y2 = c(1.25, 2.25, 1.45, 1.25, 2.25, 1.45, 1.25, 2.25, 1.45),
                        xstar = c(6.5, 10, 14, 6.5, 10, 14, 6.5, 10, 14), 
                        ystar = c(1.5, 2.5, 1.7, 1.5, 2.5, 1.7, 1.5, 2.5, 1.7),
                        lab = c("**", "***", "***",  "**", "***", "***",  "**", "***", "***"),
                        Fruit_s = c("Cherry", "Cherry", "Cherry",
                               "Cranberry", "Cranberry", "Cranberry",
                               "Strawberry", "Strawberry", "Strawberry"), 
                        Line = NA)
TEMP_anno


TEMP_title <- data.frame(xtitle = c(14, 14, 14),
                       ytitle = c(3, 3, 3),
                       title = c("Cherry", "Cranberry", "Strawberry"),
                       Fruit_s = c("Cherry", "Cranberry", "Strawberry"), 
                       Line = NA)
TEMP_title


PLOT_FITNESS_CHERRY <- ggplot(data = TEMP_total[TEMP_total$Fruit_s == "Cherry",], 
                            aes(x = factor(Generation),group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin =fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.2,color = "black") + 
  geom_line(size = 0.3,position = pd) + 
  geom_line(data = dat_predict_allfruits[dat_predict_allfruits$Fruit_s == "Cherry",], 
                     aes(x = factor(Generation), y = fitness_predicted,
                         colour = "black", group = Step), size = 0.5) + 
  geom_point(size =1, position = pd, shape =21, fill = "white") + 
  ylim(-3, 3.05) + 
  ylab("Fitness") + 
  xlab("Generation") + 
  geom_text(data = TEMP_anno[TEMP_anno$Fruit_s == "Cherry",], aes(x = xstar,  y = ystar, label = lab), size =3.3) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Cherry",], aes(x = x1, xend = x1, 
           y = y1, yend = y2), size = 0.4) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Cherry",], aes(x = x2, xend = x2, 
           y = y1, yend = y2), size = 0.4) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Cherry",], aes(x = x1, xend = x2, 
           y = y2, yend = y2), size = 0.4) + 
  scale_color_manual(values = c("black", "#BC3C6D", "#FDB424", "#3FAA96")) + 
  ggtitle("Cherry") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#BC3C6D"))
PLOT_FITNESS_CHERRY



PLOT_FITNESS_CRANB <- ggplot2::ggplot(data = TEMP_total[TEMP_total$Fruit_s == "Cranberry",], 
                            aes(x = factor(Generation),group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin =fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.2,color = "black") + 
  geom_line(size = 0.3,position = pd) + 
  geom_line(data = dat_predict_allfruits[dat_predict_allfruits$Fruit_s == "Cranberry",], aes(x = factor(Generation), y = fitness_predicted, colour = "black", group = Step),
                size = 0.5) + 
  geom_point(size =1, position = pd, shape =21, fill = "white") + 
  ylim(-3, 3.05) + 
  ylab("Fitness") + 
  xlab("Generation") + 
  geom_text(data = TEMP_anno[TEMP_anno$Fruit_s == "Cranberry",], aes(x = xstar,  y = ystar, label = lab), size =3.3) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Cranberry",], aes(x = x1, xend = x1, 
           y = y1, yend = y2), size = 0.4) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Cranberry",], aes(x = x2, xend = x2, 
           y = y1, yend = y2), size = 0.4) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Cranberry",], aes(x = x1, xend = x2, 
           y = y2, yend = y2), size = 0.4) + 
  scale_color_manual(values = c("black", "#FDB424")) + 
  ggtitle("Cranberry") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#FDB424"))
PLOT_FITNESS_CRANB



PLOT_FITNESS_STRAW <- ggplot2::ggplot(data = TEMP_total[TEMP_total$Fruit_s == "Strawberry",], 
                            aes(x = factor(Generation),group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin =fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.2,color = "black") + 
  geom_line(size = 0.3,position = pd) + 
  geom_line(data = dat_predict_allfruits[dat_predict_allfruits$Fruit_s == "Strawberry",], 
            aes(x = factor(Generation), y = fitness_predicted, colour = "black", group = Step),
            size = 0.5) + 
  geom_point(size =1, position = pd, shape =21, fill = "white") + 
  ylim(-3, 3.05) + 
  ylab("Fitness") + 
  xlab("Generation") + 
  geom_text(data = TEMP_anno[TEMP_anno$Fruit_s == "Strawberry",], 
            aes(x = xstar,  y = ystar, label = lab), size =3.3) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Strawberry",], 
               aes(x = x1, xend = x1, y = y1, yend = y2), size = 0.4) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Strawberry",], 
               aes(x = x2, xend = x2, y = y1, yend = y2), size = 0.4) + 
  geom_segment(data = TEMP_anno[TEMP_anno$Fruit_s == "Strawberry",], 
               aes(x = x1, xend = x2, y = y2, yend = y2), size = 0.4) + 
  scale_color_manual(values = c("black", "#3FAA96")) + 
  ggtitle("Strawberry") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#3FAA96"))
PLOT_FITNESS_STRAW


DYNAMIQUE_THREE_JOIN <- cowplot::ggdraw() + 
  cowplot::draw_plot(PLOT_FITNESS_CHERRY + theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank()), 
            x = 0, y = 0.66, width = 1, height = 0.33) + 
  cowplot::draw_plot(PLOT_FITNESS_CRANB + theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank()), 
            x = 0, y = 0.33, width = 1, height = 0.33) + 
  cowplot::draw_plot(PLOT_FITNESS_STRAW, 
            x = 0, y = 00, width = 1, height = 0.33) + 
  cowplot::draw_plot_label(c("A", "B", "C"),  
                  x = c(0, 0, 0), 
                  y = c(1, 0.66, 0.33), 
                  hjust = c(-0.5, -0.5, -0.5), 
                  vjust = c(1.5, 1.5, 1.5),
                  size = 12) 
 DYNAMIQUE_THREE_JOIN


cowplot::save_plot(file =here::here("figures", "FIG_Adaptation.pdf"), DYNAMIQUE_THREE_JOIN, base_height = 17/cm(1), base_width = 11/cm(1), dpi = 1200)



```







# HETEROGENEITY
## Plot 
```{r }
pd <-  position_dodge(width = 0.5)



################### INTERMEDIATE PHENOTYPING

# Re-order levels of Line
data_sum_G7 <- data_logchange[data_logchange$Generation == "7",]
data_sum_G7$Line <- factor(data_sum_G7$Line, levels= c("CE2", "CE1", "CE4", "CE3",
                                                       "CR2", "CR3", "CR5", "CR1", "CR4",
                                                       "FR2", "FR3", "FR5", "FR1", "FR4"))


#Plot: 
symp_allop_g7 <- ggplot(data = data_sum_G7, 
                      aes(x = Line, y = logchange, group = Treatment, 
                          color = Fruit_s, shape = Treatment, fill = Fruit_s)) + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey", size = 0.5) + 
  geom_errorbar(aes(ymin = logchange-1.96*sd_logchange, 
                    ymax =logchange + 1.96*sd_logchange, linetype = Line_type),
                  width = 0.2, size = 0.5, alpha = 0.6,position = pd) + 
  geom_point(position = pd, fill = "white", size =3) + 
  ylab("Fitness difference between intermediate\nand initial phenotyping steps")  + 
  xlab("Populations") + 
  labs(shape = "Test fruit", color = "Selection fruit") + 
  guides(color = FALSE,
           shape = guide_legend(override.aes = list(fill = c("black")))) + 
  scale_shape_manual(values = c(21, 22, 24)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  theme_LO_sober + theme(axis.text.x  = element_blank()) +
  coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 15),clip = "off") + 
  ggtitle("Intermediate phenotyping step") + 
  annotate("text", x = 2.5, y =1.5, label = 'bold(" Evolved\non cherry")',
                     size =3,colour = "#BC3C6D",parse = TRUE) + 
  annotate("text", x = 7.5, y =1.5, label = 'bold("   Evolved\non cranberry")',
                     size =3,colour = "#FDB424",parse = TRUE) + 
  annotate("text", x = 12.5, y =1.5, label = 'bold("   Evolved\non strawberry")',
                     size =3,colour = "#3FAA96",parse = TRUE) + 
  geom_segment(x = 15.5, y = -0.1, xend= 15.5, yend = -1.2, size = 0.15, 
               arrow = arrow(length = unit(0.05, "npc")),colour = "black") + 
  geom_segment(x = 15.5, y = 0.1, xend= 15.5, yend = 1.2, size = 0.15,
               arrow = arrow(length = unit(0.05, "npc")),colour = "black") + 
  annotate("text", x = 16.2, y = 0.5, label = 'bold(" Fitness\nincrease")',
             size =3,colour = "black",parse = TRUE, angle =90) + 
  annotate("text", x = 16.2, y =-0.5, label = 'bold("  Fitness\ndecrease")',
              size =3,colour = "black",parse = TRUE, angle =90) 
symp_allop_g7

################### FINAL PHENOTYPING

# Re-order levels of Line
data_sum_G29 <- data_logchange[data_logchange$Generation == "29",]
data_sum_G29$Line <- factor(data_sum_G29$Line, levels = c("CEA", "CEB", "CEC", 
                                                          "CRD", "CRA", "CRC", "CRB", "CRE",
                                                          "FRA", "FRC", "FRB"))

symp_allop_G29 <- ggplot(data = data_sum_G29, 
              aes(x = Line, y=logchange, group = Treatment, 
                  color =Fruit_s, shape = Treatment,fill =Fruit_s)) + 
      geom_hline(yintercept = 0, linetype = "dashed", color = "grey", size = 0.5) + 
    geom_point(size =3, position = pd) + 
    geom_errorbar(aes(ymin =logchange-1.96*sd_logchange, ymax =logchange + 1.96*sd_logchange),
                width= 0.2, size = 0.5, alpha = 0.6,position = pd) + 
    ylab("Fitness difference between final\nand initial phenotyping steps")  + 
    xlab("Populations") + 
    labs(shape = "Test fruit", color = "Selection fruit") + 
    guides(fill = FALSE, alpha = FALSE) + 
    scale_shape_manual(values = c(21, 22, 24)) + 
    scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    theme_LO_sober + theme(axis.text.x  = element_blank()) +
    coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 11),clip = "off") + 
  annotate("text", x = 2, y =1.5, label = 'bold(" Evolved\non cherry")',
                     size =3,colour = "#BC3C6D",parse = TRUE) + 
  annotate("text", x = 6, y =1.5, label = 'bold("   Evolved\non cranberry")',
                     size =3,colour = "#FDB424",parse = TRUE) + 
  annotate("text", x = 10, y =1.5, label = 'bold("   Evolved\non strawberry")',
                     size =3,colour = "#3FAA96",parse = TRUE) + 
  geom_segment(x = 11.5, y = -0.1, xend= 11.5, yend = -1.2, size = 0.15, 
               arrow = arrow(length = unit(0.05, "npc")),colour = "black") + 
    geom_segment(x = 11.5, y = 0.1, xend= 11.5, yend = 1.2, size = 0.15,
               arrow = arrow(length = unit(0.05, "npc")),colour = "black") + 
    annotate("text", x = 12, y = 0.5, label = 'bold(" Fitness\nincrease")',
             size =3,colour = "black",parse = TRUE, angle =90) + 
    annotate("text", x = 12, y = -0.5, label = 'bold("  Fitness\ndecrease")',
              size =3,colour = "black", parse = TRUE, angle =90) + 
  ggtitle("Final phenotyping step") 
symp_allop_G29




### Add stroke
DIF_FITNESS_G7 <- symp_allop_g7 + 
  geom_point(aes(alpha = SA, color = interaction(SA,Fruit_s)), position = pd, size =3, stroke =1.5, fill = "white") + 
  scale_alpha_manual(values = c(0, 1)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96", "#7C2748", "#CA8702", "#328677", "#BC3C6D", "#FDB424", "#3FAA96"))  
DIF_FITNESS_G7

DIF_FITNESS_G29 <- symp_allop_G29 + geom_point(aes(alpha = SA, color =interaction(SA,Fruit_s)), position = pd, size =3, stroke =1.5) + 
      scale_alpha_manual(values = c(0, 1)) + 
      scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96", "#7C2748", "#CA8702", "#328677", "#BC3C6D", "#FDB424", "#3FAA96"))  
DIF_FITNESS_G29


plot_legend <- ggplot(data = data_logchange, aes(x = Line, y=logchange, group = Treatment, 
                  color =Fruit_s, shape = Treatment,fill =Fruit_s)) + 
    geom_point(size =3, position = pd) + 
    labs(shape = "Test fruit", color = "Selection fruit") + 
    scale_shape_manual(values = c(21, 22, 24)) + 
    scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    theme_LO_sober + 
    guides(fill = FALSE) + 
    theme(legend.key.size = unit(0.5, "cm"),
        axis.text.x  = element_blank()) +
    coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 11),clip = "off") 


###########################################################
#############################################ALL PLOT
legend_trade <- lemon::g_legend(plot_legend)
    

SYMP_ALLOP_TOTAL <- cowplot::ggdraw() + 
  cowplot::draw_plot(DIF_FITNESS_G7 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")),
            x = 0, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot(DIF_FITNESS_G29 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")), 
            x = 0, y = 0, width = 1, height = 0.5) + 
  cowplot::draw_plot_label(c("A", "B"),  
                  x = c(0, 0), y = c(1, 0.5), 
                  size = 14) + 
  cowplot::draw_plot(legend_trade, x = 0.93, y = 0.5, width = 0.001, height = 0.001) 

SYMP_ALLOP_TOTAL


cowplot::save_plot(file =here::here("figures", "FIG_Heterogeneity.pdf"),  
                   SYMP_ALLOP_TOTAL, base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)

```



# MA-AXIS REGRESSION 
## Analysis: a supr
```{r } 
# ##### Create empty dataframe with slopes and confidence interval for all pairwise
Estimates_pairwise <- data.frame(Variables = rep(rep(c("slope", "slope_CI_inf", "slope_CI_sup",
                                                          "intercept", "intercept_CI_inf", "intercept_CI_sup"),2),3),
                                    Generation = rep(c(rep(7, 6), rep(29, 6)),3),
                                    Pairwise = rep(c("Cherry_Cranberry",
                                                     "Cranberry_Strawberry", 
                                                     "Strawberry_Cherry"), each=12),
                                    Estimates = NA)


#########################
######################### G7
#########################

####### 
#######  Cherry Cranberry
####### 


mod0_G7_CheCran <- lmodel2::lmodel2(logchange_allop ~ logchange_symp,
                    range.y = "interval",range.x = "interval",
                   data = TEMP_dataG7_CheCran, nperm=1000)
mod0_G7_CheCran

#Value:
mod0_G7_CheCran$regression.results[2,]
mod0_G7_CheCran$confidence.intervals[2,]

#Save slope, intercept and ci
Estimates_pairwise <- filldata_maregression(model = mod0_G7_CheCran,
                                                        empty_dataset = Estimates_pairwise,
                                                        generation = 7,
                                                        pairwise = "Cherry_Cranberry")



####### 
#######  Cranberry Strawberry
####### 

mod0_G7_CranStraw <- lmodel2::lmodel2(logchange_allop ~ logchange_symp, 
                    range.y = "interval",range.x = "interval",
                   data = TEMP_dataG7_CranStraw, nperm=1000)
mod0_G7_CranStraw


#Value: 
mod0_G7_CranStraw$confidence.intervals[2,]
mod0_G7_CranStraw$regression.results[2,]

#Save slope, intercept and ci 
Estimates_pairwise <- filldata_maregression(model = mod0_G7_CranStraw, 
                                                        empty_dataset = Estimates_pairwise, 
                                                        generation = 7, 
                                                        pairwise = "Cranberry_Strawberry")


####### 
#######  Strawberry  Cherry
####### 
mod0_G7_StrawChe <- lmodel2::lmodel2(logchange_allop ~ logchange_symp, 
                    range.y = "interval",range.x = "interval",
                   data = TEMP_dataG7_StrawChe, nperm=1000)
mod0_G7_StrawChe

#Value: 
mod0_G7_StrawChe$regression.results[2,]
mod0_G7_StrawChe$confidence.intervals[2,]

#Save slope, intercept and ci 
Estimates_pairwise <- filldata_maregression(model = mod0_G7_StrawChe, 
                                                        empty_dataset = Estimates_pairwise, 
                                                        generation = 7, 
                                                        pairwise = "Strawberry_Cherry")


#########################
######################### G29
######################### 


####### 
#######  Cherry Cranberry
####### 

mod0_G29_CheCran <- lmodel2::lmodel2(logchange_allop ~ logchange_symp, 
                    range.y = "interval",range.x = "interval",
                   data = TEMP_dataG29_CheCran, nperm=1000)
mod0_G29_CheCran


#Value: 
mod0_G29_CheCran$regression.results[2,]
mod0_G29_CheCran$confidence.intervals[2,]

Estimates_pairwise <- filldata_maregression(model = mod0_G29_CheCran, 
                                                        empty_dataset = Estimates_pairwise, 
                                                        generation = 29, 
                                                        pairwise = "Cherry_Cranberry")



####### 
#######  Cranberry Strawberry
####### 

mod0_G29_CranStraw <- lmodel2::lmodel2(logchange_allop ~ logchange_symp, 
                    range.y = "interval",range.x = "interval",
                   data = TEMP_dataG29_CranStraw, nperm=1000)
mod0_G29_CranStraw

#Value: 
mod0_G29_CranStraw$confidence.intervals[2,]
mod0_G29_CranStraw$regression.results[2,]

#Save slope, intercept and ci 
Estimates_pairwise <- filldata_maregression(model = mod0_G29_CranStraw, 
                                                        empty_dataset = Estimates_pairwise, 
                                                        generation = 29, 
                                                        pairwise = "Cranberry_Strawberry")


####### 
#######  Strawberry  Cherry
####### 
mod0_G29_StrawChe <- lmodel2::lmodel2(logchange_allop ~ logchange_symp, 
                    range.y = "interval",range.x = "interval",
                   data = TEMP_dataG29_StrawChe, nperm=1000)
mod0_G29_StrawChe


#Value: 
mod0_G29_StrawChe$regression.results[2,]
mod0_G29_StrawChe$confidence.intervals[2,]

#Save slope, intercept and ci 
Estimates_pairwise <- filldata_maregression(model = mod0_G29_StrawChe, 
                                                        empty_dataset = Estimates_pairwise, 
                                                        generation = 29, 
                                                        pairwise = "Strawberry_Cherry")


Estimates_pairwise
Estimates_pairwise[Estimates_pairwise$Variables == "slope",]


```



## Analysis 
```{r } 
# ##### Create empty dataframe with slopes and confidence interval for all pairwise
Estimates_pairwise <- data.frame(Variables = rep(rep(c("slope", "slope_CI_inf", "slope_CI_sup",
                                                          "intercept"),2),3),
                                    Generation = rep(c(rep(7, 4), rep(29, 4)),3),
                                    Pairwise = rep(c("Cherry_Cranberry",
                                                     "Cranberry_Strawberry", 
                                                     "Strawberry_Cherry"), each=8),
                                    Estimates = NA)

## Nbr sample 
nb_sim = 1000


#########################
######################### G7
#########################

####### 
#######  Cherry Cranberry
####### 


# MA axis regression with bootstrap to estimate slope, intercept and 
sim <- data.frame(t(sapply(1:nb_sim, bootstrap_lmodel2, data_pairwise = TEMP_dataG7_CheCran)))

# Fill out data with quantile of simulations
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="intercept"] <- quantile(sim$intercept, probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="slope"] <- quantile(sim$slope, probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="slope_CI_inf"] <- quantile(sim$slope, probs = 0.025, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="slope_CI_sup"] <- quantile(sim$slope, probs = 0.975, na.rm = TRUE)


####### 
#######  Cranberry Strawberry
####### 

# MA axis regression with bootstrap to estimate slope, intercept and 
sim <- data.frame(t(sapply(1:nb_sim, bootstrap_lmodel2, data_pairwise = TEMP_dataG7_CranStraw)))

# Fill out data with quantile of simulations
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="intercept"] <- quantile(sim$intercept,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="slope"] <- quantile(sim$slope,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="slope_CI_inf"] <- quantile(sim$slope,probs = 0.025, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="slope_CI_sup"] <- quantile(sim$slope,probs = 0.975, na.rm = TRUE)


####### 
#######  Strawberry  Cherry
####### 



# MA axis regression with bootstrap to estimate slope, intercept and 
sim <- data.frame(t(sapply(1:nb_sim, bootstrap_lmodel2, data_pairwise = TEMP_dataG7_StrawChe)))

# Fill out data with quantile of simulations
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="intercept"] <- quantile(sim$intercept,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="slope"] <- quantile(sim$slope,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="slope_CI_inf"] <- quantile(sim$slope,probs = 0.025, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==7&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="slope_CI_sup"] <- quantile(sim$slope,probs = 0.975, na.rm = TRUE)


#########################
######################### G29
######################### 


####### 
#######  Cherry Cranberry
####### 

# MA axis regression with bootstrap to estimate slope, intercept and 
sim <- data.frame(t(sapply(1:nb_sim, bootstrap_lmodel2, data_pairwise = TEMP_dataG29_CheCran)))

# Fill out data with quantile of simulations
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="intercept"] <- quantile(sim$intercept, probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="slope"] <- quantile(sim$slope, probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="slope_CI_inf"] <- quantile(sim$slope, probs = 0.025, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cherry_Cranberry"&
                              Estimates_pairwise$Variables=="slope_CI_sup"] <- quantile(sim$slope, probs = 0.975, na.rm = TRUE)



####### 
#######  Cranberry Strawberry
####### 

# MA axis regression with bootstrap to estimate slope, intercept and 
sim <- data.frame(t(sapply(1:nb_sim, bootstrap_lmodel2, data_pairwise = TEMP_dataG29_CranStraw)))

# Fill out data with quantile of simulations
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="intercept"] <- quantile(sim$intercept,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="slope"] <- quantile(sim$slope,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="slope_CI_inf"] <- quantile(sim$slope,probs = 0.025, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Cranberry_Strawberry"&
                              Estimates_pairwise$Variables=="slope_CI_sup"] <- quantile(sim$slope,probs = 0.975, na.rm = TRUE)


####### 
#######  Strawberry  Cherry
####### 
rm(sim)
# MA axis regression with bootstrap to estimate slope, intercept and 
sim <- data.frame(t(sapply(1:nb_sim, bootstrap_lmodel2, data_pairwise = TEMP_dataG29_StrawChe)))

# Fill out data with quantile of simulations
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="intercept"] <- quantile(sim$intercept,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="slope"] <- quantile(sim$slope,probs = 0.5, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="slope_CI_inf"] <- quantile(sim$slope,probs = 0.025, na.rm = TRUE)
Estimates_pairwise$Estimates[Estimates_pairwise$Generation==29&
                              Estimates_pairwise$Pairwise=="Strawberry_Cherry"&
                              Estimates_pairwise$Variables=="slope_CI_sup"] <- quantile(sim$slope,probs = 0.975, na.rm = TRUE)



Estimates_pairwise
Estimates_pairwise[Estimates_pairwise$Variables == "slope_CI_inf"|
                     Estimates_pairwise$Variables == "slope_CI_sup",]


########## 
########## ########## 
########## ########## 
########## ########## 
########## ########## 
########## ########## 
########## 
########## 
########## 
########## NEW FUNCTION 


temp_polygon_limits <- function(empty_dataset = Estimates_pairwise, generation = 7, pairwise = "Cherry_Cranberry") {

    # Limits for plot (arbitrary)
  ymin=-50
  ymax=50

  empty_dataset<-empty_dataset[empty_dataset$Generation==generation&
                                empty_dataset$Pairwise==pairwise,]
  
  # Create empty dataframe with slopes and confidence interval for all pairwise
  if (sign(empty_dataset$Estimates[empty_dataset$Variables=="slope_CI_inf"])!=
    sign(empty_dataset$Estimates[empty_dataset$Variables=="slope_CI_sup"])) {
      
    # Polygon limits
    intercept <- empty_dataset$Estimates[empty_dataset$Variables == "intercept"]
    inf_min<-(empty_dataset$Estimates[empty_dataset$Variables=="slope_CI_inf"]*ymin)+intercept
    inf_max<-(empty_dataset$Estimates[empty_dataset$Variables=="slope_CI_inf"]*ymax)+intercept
    sup_min <- (ymin-intercept)/empty_dataset$Estimates[empty_dataset$Variables == "slope_CI_sup"]
    sup_max <- (ymax-intercept)/empty_dataset$Estimates[empty_dataset$Variables == "slope_CI_sup"]



    # Dataframe with coordiantes
    polygon_data <- data.frame (xvalue = c(ymin, sup_min,
                                           sup_max,ymax),
                                yvalue = c(inf_min,ymin,
                                           ymax, inf_max))

  } else {
    # Polygon limits
    intercept <- empty_dataset$Estimates[empty_dataset$Variables == "intercept"]
    inf_min <- (ymin-intercept)/empty_dataset$Estimates[empty_dataset$Variables == "slope_CI_inf"]
    inf_max <- (ymax-intercept)/empty_dataset$Estimates[empty_dataset$Variables == "slope_CI_inf"]
    sup_min <- (ymin-intercept)/empty_dataset$Estimates[empty_dataset$Variables == "slope_CI_sup"]
    sup_max <- (ymax-intercept)/empty_dataset$Estimates[empty_dataset$Variables == "slope_CI_sup"]

    # Dataframe with coordiantes
    polygon_data <- data.frame (xvalue = c(inf_min,sup_min,
                                           sup_max,inf_max),
                                yvalue = c(ymin, ymin,
                                           ymax, ymax))
  }


  return(polygon_data)


}


```


## Plot 
```{r } 
ymin =-50
ymax =50


##################################################
##################   G7
# Calculate polygon limits and plot limits
#polygon_CheCranG7<-filldata_predict_maregression(model = mod0_G7_CheCran)
polygon_CheCranG7<-temp_polygon_limits(Estimates_pairwise, 7, "Cherry_Cranberry")

ymin_CheCranG7=min(min(TEMP_dataG7_CheCran$logchange_allop-1.96*TEMP_dataG7_CheCran$sd_allop, na.rm= TRUE),
                min(TEMP_dataG7_CheCran$logchange_symp-1.96*TEMP_dataG7_CheCran$sd_symp, na.rm= TRUE))
ymax_CheCranG7=max(max(TEMP_dataG7_CheCran$logchange_allop + 1.96*TEMP_dataG7_CheCran$sd_allop, na.rm= TRUE),
                max(TEMP_dataG7_CheCran$logchange_symp + 1.96*TEMP_dataG7_CheCran$sd_symp, na.rm= TRUE))

# Plot
CheCran_G7 <- ggplot() + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "slope"],
              colour = "black", size = 0.75) + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "slope_CI_inf"],
               colour = "grey", linetype = "dotted") + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "intercept"],
              slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "slope_CI_sup"],
              colour = "grey", linetype = "dotted") + 
  geom_errorbar(data = TEMP_dataG7_CheCran,
                aes(x = logchange_symp, ymin = logchange_allop-(1.96*sd_allop),
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp, linetype = Line_type),
                  width= 0.02, size = 0.3, alpha = 0.8) + 
  geom_errorbarh(data = TEMP_dataG7_CheCran,
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp, linetype = Line_type),
                 height = 0.02, size = 0.3, alpha = 0.8) + 
  geom_point(data = TEMP_dataG7_CheCran,
                 aes(x = logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size =3, fill = "white", stroke =1.2) + 
  xlab("Fitness difference in\nselective environment")  + 
  ylab("Fitness difference in\nalternative environment")  + 
  ggtitle("Cherry vs. Cranberry") + 
  theme_LO_sober + 
  labs(shape = "Test fruit", color = "Evolution fruit") + 
  geom_polygon(data = polygon_CheCranG7, aes(x = xvalue, y = yvalue), fill = "grey", alpha = 0.2) + 
  scale_shape_manual(values = c(21, 22)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424"))  + 
  coord_cartesian(ylim = c(ymin_CheCranG7, ymax_CheCranG7), 
                  xlim = c(ymin_CheCranG7, ymax_CheCranG7)) 
 CheCran_G7


# Calculate polygon limits and plot limits
#polygon_CranStrawG7<-filldata_predict_maregression(model = mod0_G7_CranStraw)
polygon_CranStrawG7<-temp_polygon_limits(Estimates_pairwise, 7, "Cranberry_Strawberry")

 ymin_CranStrawG7=min(min(TEMP_dataG7_CranStraw$logchange_allop-1.96*TEMP_dataG7_CranStraw$sd_allop, na.rm= TRUE),
                min(TEMP_dataG7_CranStraw$logchange_symp-1.96*TEMP_dataG7_CranStraw$sd_symp, na.rm= TRUE))
ymax_CranStrawG7=max(max(TEMP_dataG7_CranStraw$logchange_allop + 1.96*TEMP_dataG7_CranStraw$sd_allop, na.rm= TRUE),
                max(TEMP_dataG7_CranStraw$logchange_symp + 1.96*TEMP_dataG7_CranStraw$sd_symp, na.rm= TRUE))

CranStraw_G7 <-  ggplot() + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "slope"],
              colour = "black", size = 0.75) + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "slope_CI_inf"],
               colour = "grey", linetype = "dotted") + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry"  & 
                               Estimates_pairwise$Variables == "intercept"],
              slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7  & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry"  & 
                               Estimates_pairwise$Variables == "slope_CI_sup"],
              colour = "grey", linetype = "dotted") + 
  geom_errorbar(data = TEMP_dataG7_CranStraw,            
                aes(x =logchange_symp, ymin = logchange_allop-(1.96*sd_allop), 
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp, linetype = Line_type),
                  width= 0.02, size = 0.3, alpha = 0.8) + 
  geom_errorbarh(data = TEMP_dataG7_CranStraw,
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp, linetype = Line_type),
                 height = 0.02, size = 0.3, alpha = 0.8) + 
  geom_point(data = TEMP_dataG7_CranStraw,
                      aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                   size =3, fill = "white", stroke =1.2) + 
  geom_polygon(data =polygon_CranStrawG7, aes(x = xvalue, y = yvalue), fill = "grey", alpha = 0.2) + 
  xlab("Fitness difference in\nselective environment")  + 
  ylab("Fitness difference in\nalternative environment")  + 
     ggtitle("Cranberry vs. Strawberry") + 
  coord_cartesian(ylim = c(ymin_CranStrawG7, ymax_CranStrawG7), 
                  xlim = c(ymin_CranStrawG7, ymax_CranStrawG7)) + 
   labs(shape = "Test fruit", color = "Selection fruit") + 
   scale_shape_manual(values = c(22, 24)) + 
   scale_color_manual(values = c("#FDB424", "#3FAA96"))  + 
  theme_LO_sober
 CranStraw_G7

 
#Calculate polygon limits and plot limits
#polygon_StrawCheG7<-filldata_predict_maregression(model = mod0_G7_StrawChe)
polygon_StrawCheG7<-temp_polygon_limits(Estimates_pairwise, 7, "Strawberry_Cherry")

 ymin_StrawCheG7=min(min(TEMP_dataG7_StrawChe$logchange_allop-1.96*TEMP_dataG7_StrawChe$sd_allop, na.rm= TRUE),
                min(TEMP_dataG7_StrawChe$logchange_symp-1.96*TEMP_dataG7_StrawChe$sd_symp, na.rm= TRUE))
ymax_StrawCheG7=max(max(TEMP_dataG7_StrawChe$logchange_allop + 1.96*TEMP_dataG7_StrawChe$sd_allop, na.rm= TRUE),
                max(TEMP_dataG7_StrawChe$logchange_symp + 1.96*TEMP_dataG7_StrawChe$sd_symp, na.rm= TRUE))

StrawChe_G7 <-  ggplot() + 
    geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "slope"],
              colour = "black", size = 0.75) + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "slope_CI_inf"],
               colour = "grey", linetype = "dotted") + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "intercept"],
              slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation == 7 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "slope_CI_sup"],
              colour = "grey", linetype = "dotted") + 
  geom_errorbar(data = TEMP_dataG7_StrawChe,
                aes(x =logchange_symp, ymin = logchange_allop-(1.96*sd_allop), ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp, linetype = Line_type),
                  width= 0.02, size = 0.3, alpha = 0.8) + 
  geom_errorbarh(data = TEMP_dataG7_StrawChe,
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp, linetype = Line_type),
                 height = 0.02, size = 0.3, alpha = 0.8) + 
  geom_point(data = TEMP_dataG7_StrawChe,
                 aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size =3, fill = "white", stroke =1.2) + 
  geom_polygon(data =polygon_StrawCheG7, aes(x = xvalue, y = yvalue), fill = "grey", alpha = 0.2) + 
    xlab("Fitness difference in\nselective environment")  + 
    ylab("Fitness difference in\nalternative environment")  + 
  ggtitle("Strawberry vs. Cherry") + 
  labs(shape = "Test fruit", color = "Selection fruit") + 
  scale_shape_manual(values = c(21, 24)) + 
  scale_color_manual(values = c("#BC3C6D", "#3FAA96"))  + 
  coord_cartesian(ylim = c(ymin_StrawCheG7, ymax_StrawCheG7), 
                  xlim = c(ymin_StrawCheG7, ymax_StrawCheG7)) + 
  theme_LO_sober
 StrawChe_G7
 
 
  
#####################################################################################
##################################      G29        ##################################
#####################################################################################
TEMP_dataG29_CheCran
TEMP_dataG29_CranStraw
TEMP_dataG29_StrawChe


#Calculate polygon limits and plot limits
polygon_CheCranG29<-filldata_predict_maregression(model = mod0_G29_CheCran)
polygon_CheCranG29<-temp_polygon_limits(Estimates_pairwise, 29, "Cherry_Cranberry")

ymin_CheCranG29=min(min(TEMP_dataG29_CheCran$logchange_allop-1.96*TEMP_dataG29_CheCran$sd_allop, na.rm= TRUE),
                min(TEMP_dataG29_CheCran$logchange_symp-1.96*TEMP_dataG29_CheCran$sd_symp, na.rm= TRUE))
ymax_CheCranG29=max(max(TEMP_dataG29_CheCran$logchange_allop + 1.96*TEMP_dataG29_CheCran$sd_allop, na.rm= TRUE),
                max(TEMP_dataG29_CheCran$logchange_symp + 1.96*TEMP_dataG29_CheCran$sd_symp, na.rm= TRUE))


CheCran_G29 <- ggplot() + 
    geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "slope"],
              colour = "black", size = 0.75) + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "slope_CI_inf"],
               colour = "grey", linetype = "dotted") + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "intercept"],
              slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cherry_Cranberry" & 
                               Estimates_pairwise$Variables == "slope_CI_sup"],
              colour = "grey", linetype = "dotted") + 
  geom_errorbar(data = TEMP_dataG29_CheCran,
                aes(x =logchange_symp, ymin = logchange_allop-(1.96*sd_allop), 
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp),
                  width= 0.02, size = 0.3, alpha = 0.8) + 
  geom_errorbarh(data = TEMP_dataG29_CheCran,
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp),
                 height = 0.02, size = 0.3, alpha = 0.8) + 
  geom_point(data = TEMP_dataG29_CheCran,
                 aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size =3, fill = "white", stroke =1.2) + 
  geom_polygon(data =polygon_CheCranG29, aes(x = xvalue, y = yvalue), fill = "grey", alpha = 0.2) + 
    xlab("Fitness difference in\nselective environment")  + 
    ylab("Fitness difference in\nalternative environment")  + 
  ggtitle("Cherry vs. Cranberry") + 
  labs(shape = "Test fruit", color = "Evolution fruit") + 
  scale_shape_manual(values = c(16, 15)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424"))  + 
  coord_cartesian(ylim = c(ymin_CheCranG29, ymax_CheCranG29), 
                  xlim = c(ymin_CheCranG29, ymax_CheCranG29)) + 
  theme_LO_sober
 CheCran_G29



#Calculate polygon limits and plot limits
polygon_CranStrawG29<-filldata_predict_maregression(model = mod0_G29_CranStraw)
polygon_CranStrawG29<-temp_polygon_limits(Estimates_pairwise, 29, "Cranberry_Strawberry")

ymin_CranStrawG29=min(min(TEMP_dataG29_CranStraw$logchange_allop-1.96*TEMP_dataG29_CranStraw$sd_allop, na.rm= TRUE),
                min(TEMP_dataG29_CranStraw$logchange_symp-1.96*TEMP_dataG29_CranStraw$sd_symp, na.rm= TRUE))
ymax_CranStrawG29=max(max(TEMP_dataG29_CranStraw$logchange_allop + 1.96*TEMP_dataG29_CranStraw$sd_allop, na.rm= TRUE),
                max(TEMP_dataG29_CranStraw$logchange_symp + 1.96*TEMP_dataG29_CranStraw$sd_symp, na.rm= TRUE))

#Plot
 CranStraw_G29 <- ggplot() + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "slope"],
              colour = "black", size = 0.75) + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "slope_CI_inf"],
               colour = "grey", linetype = "dotted") + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "intercept"],
              slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Cranberry_Strawberry" & 
                               Estimates_pairwise$Variables == "slope_CI_sup"],
                            colour = "grey", linetype = "dotted") + 
   geom_errorbar(data = TEMP_dataG29_CranStraw,
                aes(x =logchange_symp, ymin = logchange_allop-(1.96*sd_allop), 
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp),
                  width= 0.02, size = 0.3, alpha = 0.8) + 
   geom_errorbarh(data = TEMP_dataG29_CranStraw,
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp),
                 height = 0.02, size = 0.3, alpha = 0.8) + 
   geom_point(data = TEMP_dataG29_CranStraw,
                 aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size =3, fill = "white", stroke =1.2) + 
   geom_polygon(data =polygon_CranStrawG29, aes(x = xvalue, y = yvalue), fill = "grey", alpha = 0.2) + 
    xlab("Fitness difference in\nselective environment")  + 
    ylab("Fitness difference in\nalternative environment")  + 
   ggtitle("Cranberry vs. Strawberry") + 
   coord_cartesian(ylim = c(ymin_CranStrawG29, ymax_CranStrawG29), 
                  xlim = c(ymin_CranStrawG29, ymax_CranStrawG29)) + 
   labs(shape = "Test fruit", color = "Selection fruit") + 
   scale_shape_manual(values = c(15, 17)) + 
   scale_color_manual(values = c("#FDB424", "#3FAA96"))  + 
   theme_LO_sober
 CranStraw_G29

 
 
 
 

#Calculate polygon limits and plot limits
polygon_StrawCheG29<-filldata_predict_maregression(model = mod0_G29_StrawChe)
polygon_StrawCheG29<-temp_polygon_limits(Estimates_pairwise, 29, "Strawberry_Cherry")

ymin_StrawCheG29=min(min(TEMP_dataG29_StrawChe$logchange_allop-1.96*TEMP_dataG29_StrawChe$sd_allop, na.rm= TRUE),
                min(TEMP_dataG29_StrawChe$logchange_symp-1.96*TEMP_dataG29_StrawChe$sd_symp, na.rm= TRUE))
ymax_StrawCheG29=max(max(TEMP_dataG29_StrawChe$logchange_allop + 1.96*TEMP_dataG29_StrawChe$sd_allop, na.rm= TRUE),
                max(TEMP_dataG29_StrawChe$logchange_symp + 1.96*TEMP_dataG29_StrawChe$sd_symp, na.rm= TRUE))


StrawChe_G29 <- ggplot() + 
 geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "slope"],
              colour = "black", size = 0.75) + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "intercept"],
               slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "slope_CI_inf"],
               colour = "grey", linetype = "dotted") + 
  geom_abline(intercept = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "intercept"],
              slope = Estimates_pairwise$Estimates[Estimates_pairwise$Generation ==29 & 
                               Estimates_pairwise$Pairwise == "Strawberry_Cherry" & 
                               Estimates_pairwise$Variables == "slope_CI_sup"],
                            colour = "grey", linetype = "dotted") + 
  geom_errorbar(data = TEMP_dataG29_StrawChe,
                aes(x =logchange_symp, ymin = logchange_allop-(1.96*sd_allop), 
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp),
                  width= 0.02, size = 0.2, alpha =1) + 
   geom_errorbarh(data = TEMP_dataG29_StrawChe,
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp),
                 height = 0.02, size = 0.2, alpha =1) + 
  geom_point(data = TEMP_dataG29_StrawChe,
                 aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size =3, fill = "white", stroke =1.2) + 
  geom_polygon(data =polygon_StrawCheG29, aes(x = xvalue, y = yvalue), fill = "grey", alpha = 0.2) + 
  coord_cartesian(ylim = c(ymin_StrawCheG29, ymax_StrawCheG29), 
                  xlim = c(ymin_StrawCheG29, ymax_StrawCheG29)) + 
    xlab("Fitness difference in\nselective environment")  + 
    ylab("Fitness difference in\nalternative environment")  + 
  ggtitle("Strawberry vs. Cherry") + 
  labs(shape = "Test fruit", color = "Selection fruit") + 
  scale_shape_manual(values = c(16, 17)) + 
  scale_color_manual(values = c("#BC3C6D", "#3FAA96"))  + 
  theme_LO_sober
 StrawChe_G29





 
 
legend_tradevide <-  ggplot(data = data_logchange[data_logchange$Generation == "29",],
                          aes(x =logchange, y = logchange,  color = Symp,fill = Symp, shape = Allop)) + 
  geom_point(size =2.5, fill = "white") + 
  labs(shape = "Test fruit", color = "Selection fruit") + 
  scale_shape_manual(values = c(16, 15, 17)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  theme_LO_sober

legend_trade <- lemon::g_legend(legend_tradevide)

 
 

Slopeestimates_logchange_pairwise_errorbar <- cowplot::ggdraw() + 
  cowplot::draw_plot(CheCran_G7 + theme(legend.position = "none"), 
            x = 0.00, y = 0.5, width = 0.22, height = 0.45) + 
  cowplot::draw_plot(CranStraw_G7 + theme(legend.position = "none"), 
            x = 0.26, y = 0.5, width = 0.22, height = 0.45) + 
  cowplot::draw_plot(StrawChe_G7 + theme(legend.position = "none"), 
            x = 0.52, y = 0.5, width = 0.22, height = 0.45) + 
  cowplot::draw_plot(legend_trade, x = 0.750, y = 0.5, width = 0.1, height = 0.1) + 
  cowplot::draw_plot(CheCran_G29 + theme(legend.position = "none"), 
            x = 0.00, y = 0, width = 0.22, height = 0.45) + 
  cowplot::draw_plot(CranStraw_G29 + theme(legend.position = "none"), 
            x = 0.26, y = 0, width = 0.22, height = 0.45) + 
  cowplot::draw_plot(StrawChe_G29 + theme(legend.position = "none"), 
            x = 0.52, y = 0, width = 0.22, height = 0.45) + 
  cowplot::draw_plot_label(c("Intermediate phenotyping step", "A", "B", "C", " ",
                    "Final phenotyping step", "D", "E", "F", " "),  
                  x = c(0.26, 0, 0.26, 0.52, 0.82, 0.2, 0, 0.26, 0.52, 0.82), 
                  y = c(1, 0.95, 0.95, 0.95, 0.95, 0.5, 0.45, 0.45, 0.45, 0.45), 
                  hjust = c(-0.25, -0.25, -0.25, -0.25, -0.25, -0.75, -0.75, -0.75, -0.75, -0.75), 
                  vjust = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5),
                  size = 14) 
 Slopeestimates_logchange_pairwise_errorbar
#  
# #  
# 
cowplot::save_plot(file =here::here("figures", "FIG_MAregression.pdf"),
                   Slopeestimates_logchange_pairwise_errorbar,
                   base_height = 15/cm(1), base_width = 30/cm(1), dpi = 610)




```

# SA AND LOCAL ADAPTATION
## Analysis
```{r }
##### 
#####  G7
##### 
# Pblm when Nb_adults= 0, it is impossible to calculate fitness log(0/20)
data_G7[data_G7$Nb_adults == 0,]
# correspond to 2 allopatric and 2 sympatric measurements (2 in CE1, 1 in FR4 et 1 in FR1)

# Remove Nb_adults = 0 because it is negligeable
data_G7_without0 <- data_G7[data_G7$Nb_adults!= 0,]
data_G7_without0$fitness <- log(data_G7_without0$Nb_adults/20)

lm_val_G7 = lm(fitness ~ Treatment + Line + SA + Treatment:Fruit_s, data = data_G7_without0)

Fratio = anova(lm_val_G7)[3, 3]/anova(lm_val_G7)[4, 3]
pvalue = 1 - pf(Fratio, anova(lm_val_G7)[3, 1], anova(lm_val_G7)[4, 1]) 

pvalue
Fratio
anova(lm_val_G7)[3, 1]
anova(lm_val_G7)[4, 1]

##### 
#####  G29
##### 

# Pblm when Nb_adults= 0, it is impossible to calculate fitness log(0/20)
data_G29[data_G29$Nb_adults == 0,]
length(data_G29[data_G29$Nb_adults == 0 & data_G29$SA == 0,]$Nb_adults)
length(data_G29[data_G29$Nb_adults == 0 & data_G29$SA == 1,]$Nb_adults)
# correspond to 25 measures 17 allopatric and 8 sympatric measurements (2 in CE1, 1 in FR4 et 1 in FR1)

# Remove Nb_adults = 0 because it is negligeable
data_G29_without0 <- data_G29[data_G29$Nb_adults!= 0,]
data_G29_without0$fitness <- log(data_G29_without0$Nb_adults/20)

lm_val_G29 = lm(fitness ~ Treatment + Line + SA + Treatment:Fruit_s, data = data_G29_without0)

Fratio = anova(lm_val_G29)[3, 3]/anova(lm_val_G29)[4, 3]
pvalue = 1 - pf(Fratio, anova(lm_val_G29)[3, 1], anova(lm_val_G29)[4, 1]) 

pvalue
Fratio
anova(lm_val_G29)[3, 1]
anova(lm_val_G29)[4, 1]

```

