---
title: "Simulation of log fitness change"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```

# DATA
```{r }
## Longitudinal data
data_sum <- loadlongitudinaldata(dataset = "DATA_Adults_G1G29.csv", rm_generation1 = 1,rm_generation2 = 7,rm_generation3 = 29)

## Phenotyping steps
data_G0 <- loadfitnessdata(dataset = "Selection_Phenotypage_G0_G7_G8.csv", generation = "G1")
data_G7 <- loadfitnessdata(dataset = "Selection_Phenotypage_G0_G7_G8.csv", generation = "G7")
data_G29 <- loadfitnessdata(dataset = 
                            "PERFORMANCE_Comptage_adultes_G13G14G15G16G17G18G19G20G21G22G23G24G25G26G27G28G29.csv",
                            generation = "29")


#Compute log change
data_logchange<-computelogchange(fitness_dataset_intermediate = data_G7, fitness_dataset_final = data_G29)
#Lines: CE2 and CR2 do not pass Geary's test (the threshold of a standardized mean greater than 3)
data_logchange$Line_type  <- ifelse(data_logchange$Line == "CR2"| data_logchange$Line == "CE2", "solid","dashed")


#Formatting for plotting pairwise of fitness change
EC_Cran_Cher_G7<-formattingplotpair(data_logchange, "7", "Cherry", "Cranberry")
EC_Straw_Cran_G7<-formattingplotpair(data_logchange, "7", "Cranberry", "Strawberry")
EC_Straw_Cher_G7<-formattingplotpair(data_logchange, "7", "Strawberry", "Cherry")
EC_Cran_Cher_G29<-formattingplotpair(data_logchange, "29", "Cherry", "Cranberry")
EC_Straw_Cran_G29<-formattingplotpair(data_logchange, "29", "Cranberry", "Strawberry")
EC_Straw_Cher_G29<-formattingplotpair(data_logchange, "29", "Strawberry", "Cherry")


#Formatting for plot pool
TEMP_dataG29_CheCran <- formattinglogchange(data_logchange, "29", "Cherry", "Cranberry")
TEMP_dataG29_CranStraw <- formattinglogchange(data_logchange, "29", "Cranberry", "Strawberry")
TEMP_dataG29_StrawChe <- formattinglogchange(data_logchange, "29", "Strawberry", "Cherry")




## Data longitudinal 
data_sum_allfruits <- loadlongitudinaldata_allfruits(dataset = "DATA_Adults_G1G29.csv", rm_generation_max = 5)
data_sum_allfruits_AN<-data_sum_allfruits[data_sum_allfruits$Generation!=1,]
```





# SUP: Pairwise fitness change
## Plot 
```{r } 
#Limit axis 
lim_G7<-max(abs(min(data_logchange[data_logchange$Generation=="7",]$logchange-
                      1.96*data_logchange[data_logchange$Generation=="7",]$sd_logchange, na.rm = T)),
            max(data_logchange[data_logchange$Generation=="7",]$logchange+
                  1.96*data_logchange[data_logchange$Generation=="7",]$sd_logchange, na.rm = T))

lim_G29<-max(abs(min(data_logchange[data_logchange$Generation=="29",]$logchange-
                       1.96*data_logchange[data_logchange$Generation=="29",]$sd_logchange, na.rm = T)),
            max(data_logchange[data_logchange$Generation=="29",]$logchange+
                  1.96*data_logchange[data_logchange$Generation=="29",]$sd_logchange, na.rm = T))

#Plot
PAIR_StrawCran_G7<-ggplot(data = EC_Straw_Cran_G7,
                          aes(x = logchange_Strawberry,y = logchange_Cranberry, color=Fruit_s)) +
  geom_errorbar(aes(ymin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                    ymax = logchange_Cranberry+1.96*sd_logchange_Cranberry, linetype=Line_type),
                width=0.02,size=0.2,alpha=1) + 
  geom_errorbarh(aes(xmin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                     xmax = logchange_Strawberry+1.96*sd_logchange_Strawberry, linetype=Line_type),
                 height=0.02,size=0.2,alpha=1) + 
  geom_point(shape=21, size=3,  fill = "#ffffff", stroke=1.3) + 
  xlab("Fitness change\nin strawberry")  +     
  ylab("Fitness change\nin cranberry")  +
  xlim(-lim_G7,lim_G7) + 
  ylim(-lim_G7,lim_G7) +  
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  theme(axis.title.x = element_text(size=10, colour = "#3FAA96"),
        axis.title.y = element_text(size=10, colour = "#FDB424")) +
  theme_LO_sober
 PAIR_StrawCran_G7

 
 
PAIR_StrawChe_G7<-ggplot(data = EC_Straw_Cher_G7,
                         aes(x = logchange_Cherry,y = logchange_Strawberry, color=Fruit_s)) + 
  geom_errorbar(aes(ymin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                    ymax = logchange_Strawberry+1.96*sd_logchange_Strawberry, linetype=Line_type),
                  width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(aes(xmin = logchange_Cherry-1.96*sd_logchange_Cherry,
                     xmax = logchange_Cherry+1.96*sd_logchange_Cherry, linetype=Line_type),
                  height=0.02, size=0.2, alpha=1) + 
  geom_point(shape=21, size=3,  fill = "#ffffff", stroke=1.3) + 
  ylab("Fitness change\nin strawberry")  + 
  xlab("Fitness change\nin cherry")  + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  xlim(-lim_G7,lim_G7) + 
  ylim(-lim_G7,lim_G7) +    
  theme(axis.title.x = element_text(size=10, colour = "#BC3C6D"),
           axis.title.y = element_text(size=10, colour = "#3FAA96")) +
  theme_LO_sober
 PAIR_StrawChe_G7



 
PAIR_CheCran_G7<-ggplot(data = EC_Cran_Cher_G7,aes(x = logchange_Cranberry,y = logchange_Cherry, 
                                          color=Fruit_s)) + 
  geom_errorbar(aes(ymin = logchange_Cherry-1.96*sd_logchange_Cherry,
                      ymax = logchange_Cherry+1.96*sd_logchange_Cherry, linetype=Line_type),
                  width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(aes(xmin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                       xmax = logchange_Cranberry+1.96*sd_logchange_Cranberry, linetype=Line_type),
                  height=0.02, size=0.2, alpha=1) + 
  geom_point(shape=21, size=3,  fill = "#ffffff", stroke=1.3) + 
  ylab("Fitness change\nin cherry")  + 
  xlab("Fitness change\nin cranberry")  + 
  xlim(-lim_G7, lim_G7) + 
  ylim(-lim_G7, lim_G7) +     
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  theme_LO_sober + 
  theme(axis.title.x = element_text(colour = "#FDB424"),
        axis.title.y = element_text(colour = "#BC3C6D")) 
 PAIR_CheCran_G7



################## Final phenotyping step
#Plot
PAIR_CranStraw_G29<-ggplot(data = EC_Straw_Cran_G29,
                          aes(x = logchange_Strawberry, y = logchange_Cranberry,  color=Fruit_s)) + 
  geom_errorbar(aes(ymin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                      ymax = logchange_Cranberry+1.96*sd_logchange_Cranberry, linetype=Line_type),
                  width=0.02,size=0.2,alpha=1) + 
  geom_errorbarh(aes(xmin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                       xmax = logchange_Strawberry+1.96*sd_logchange_Strawberry, linetype=Line_type),
                  height=0.02,size=0.2,alpha=1) + 
  geom_point(aes(fill = Fruit_s),shape=21, size=3) + 
  xlab("Fitness change\nin strawberry")  +     
  ylab("Fitness change\nin cranberry")  +
  xlim(-lim_G29,lim_G29) + 
  ylim(-lim_G29,lim_G29) +     
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  scale_fill_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  theme(axis.title.x = element_text(size=10, colour = "#3FAA96"),
        axis.title.y = element_text(size=10, colour = "#FDB424")) +
  theme_LO_sober
 PAIR_CranStraw_G29

 
 
PAIR_StrawChe_G29<-ggplot(data = EC_Straw_Cher_G29,
                         aes(x = logchange_Cherry,y = logchange_Strawberry,  color=Fruit_s)) + 
  geom_errorbar(aes(ymin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                      ymax = logchange_Strawberry+1.96*sd_logchange_Strawberry, linetype=Line_type),
                  width=0.02,size=0.2,alpha=1) + 
  geom_errorbarh(aes(xmin = logchange_Cherry-1.96*sd_logchange_Cherry,
                       xmax = logchange_Cherry+1.96*sd_logchange_Cherry, linetype=Line_type),
                  height=0.02,size=0.2,alpha=1) + 
  geom_point(aes(fill = Fruit_s),shape=21, size=3) + 
  ylab("Fitness change\nin strawberry")  + 
  xlab("Fitness change\nin cherry")  + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  scale_fill_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  xlim(-lim_G29,lim_G29) + 
  ylim(-lim_G29,lim_G29) +       
  theme(axis.title.x = element_text(colour = "#BC3C6D"),
           axis.title.y = element_text(colour = "#3FAA96")) +
  theme_LO_sober
 PAIR_StrawChe_G29


 
PAIR_CheCran_G29<-ggplot(data = EC_Cran_Cher_G29,
                         aes(x = logchange_Cranberry,y = logchange_Cherry, color=Fruit_s)) + 
  geom_errorbar(aes(ymin = logchange_Cherry-1.96*sd_logchange_Cherry,
                      ymax = logchange_Cherry+1.96*sd_logchange_Cherry, linetype=Line_type),
                  width=0.02,size=0.2,alpha=1) + 
  geom_errorbarh(aes(xmin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                       xmax = logchange_Cranberry+1.96*sd_logchange_Cranberry, linetype=Line_type),
                  height=0.02,size=0.2,alpha=1) + 
  geom_point(aes(fill = Fruit_s), shape=21, size=3) + 
  ylab("Fitness change\nin cherry")  + 
  xlab("Fitness change\nin cranberry")  + 
  xlim(-lim_G29,lim_G29) + 
  ylim(-lim_G29,lim_G29) +   
  scale_fill_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96"))  + 
  theme_LO_sober + 
  theme(axis.title.x = element_text(colour = "#FDB424"),
        axis.title.y = element_text(colour = "#BC3C6D")) 
 PAIR_CheCran_G29


 #Legend
TEMP_data_logchange_sum_Straw_Cher_G7<-data_logchange
TEMP_data_logchange_sum_Straw_Cher_G7$Pheno<-sample(c("Intermediate", "Final"),
                                                    length(data_logchange$logchange), 
                                                    replace=TRUE)

PAIR_plot_legend<- ggplot(data=TEMP_data_logchange_sum_Straw_Cher_G7, 
                          aes(x=Treatment, y=logchange, group=Fruit_s, colour=Fruit_s,shape=Pheno)) +
  geom_errorbar(aes(ymin=logchange-1.96*sd_logchange, ymax=logchange+1.96*sd_logchange),
                  width=0.01,size=1) +
  geom_point(size=3, stroke=1.3) + 
  scale_shape_manual(name = "Phenotyping step", 
                     labels = c("Intermediate", "Final"),values=c(21,16)) +
  scale_color_manual(name= "Selection fruit", 
                     values=c("#BC3C6D", "#FDB424", "#3FAA96"), 
                     label=c("Cherry", "Cranberry", "Strawberry")) +   
  theme_LO_sober
PAIR_legend<-lemon::g_legend(PAIR_plot_legend)

rm(TEMP_data_logchange_sum_Straw_Cher_G7)




PAIR_Fig_Sup <-  cowplot::ggdraw() +
  cowplot::draw_plot(PAIR_CheCran_G7+theme(legend.position = "none"), 
            x =0.00, y = 0.5, width = 0.22, height =0.45) +
  cowplot::draw_plot(PAIR_StrawCran_G7+theme(legend.position = "none"), 
            x = 0.26, y = 0.5, width = 0.22, height = 0.45) +
  cowplot::draw_plot(PAIR_StrawChe_G7+theme(legend.position = "none"), 
            x = 0.52, y = 0.5, width = 0.22, height = 0.45) + 
  cowplot::draw_plot(PAIR_legend, x = 0.80, y = 0.5, width = 0.1, height = 0.1) +
  cowplot::draw_plot(PAIR_CheCran_G29+theme(legend.position = "none"), 
            x =0.00, y = 0, width = 0.22, height = 0.45) +
  cowplot::draw_plot(PAIR_CranStraw_G29+theme(legend.position = "none"), 
            x = 0.26, y = 0, width = 0.22, height = 0.45) +
  cowplot::draw_plot(PAIR_StrawChe_G29+theme(legend.position = "none"), 
            x = 0.52, y = 0, width = 0.22, height = 0.45) + 
  cowplot::draw_plot_label(c("Intermediate phenotyping step", "A", "B", "C", " ",
                    "Final phenotyping step", "D", "E", "F", " "),  
                  x = c(0.26,0,0.26,0.52,0.82,0.2,0,0.26,0.52,0.82), 
                  y = c(1.01,0.97,0.97,0.97,0.97,0.5,0.47, 0.47, 0.47, 0.47), 
                  hjust = c(-0.25,-0.25,-0.25,-0.25,-0.25,-0.75,-0.75,-0.75,-0.75,-0.75), 
                  vjust = c(1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5),
                  size = 14) 
 PAIR_Fig_Sup
 

cowplot::save_plot(file=here::here("figures", "SUPMAT_LogChange_Pairwise.pdf"), PAIR_Fig_Sup, 
                   base_height = 15/cm(1), base_width = 30/cm(1), dpi = 610)


```

# Traits
## Correlation between Nb_eggs and emergence_rate
```{r }
tapply(data_G0$Nb_eggs, data_G0$Treatment, mean)
diag(tapply(data_G7$Nb_eggs, list(data_G7$Treatment,data_G7$Fruit_s), mean))
diag(tapply(data_G29$Nb_eggs, list(data_G29$Treatment,data_G29$Fruit_s), mean))


tapply(data_G0$Emergence_rate, data_G0$Treatment, mean)
diag(tapply(data_G7$Emergence_rate, list(data_G7$Treatment,data_G7$Fruit_s), mean))
diag(tapply(data_G29$Emergence_rate, list(data_G29$Treatment,data_G29$Fruit_s), mean))

## Compute correlation by generation and selective fruit
ddply(data_logchangeNb_eggsEmergence_rate, .(Generation, Fruit_s), computecorrelation)


#Plot

Nb_eggsEmergence_rateG7 <- ggplot(data = data_logchangeNb_eggsEmergence_rate[data_logchangeNb_eggsEmergence_rate$Generation==7,],
                          aes(x = Nb_eggslogchange,y = Emergence_ratelogchange, group = Treatment, shape = Treatment)) +
  geom_errorbarh(aes(xmin = Nb_eggslogchange-1.96*sdNb_eggslogchange,
                     xmax = Nb_eggslogchange+1.96*sdNb_eggslogchange),
                 height=0.02,size=0.2,alpha=1) +
  geom_errorbar(aes(ymin = Emergence_ratelogchange-1.96*sdEmergence_ratelogchange,
                    ymax = Emergence_ratelogchange+1.96*sdEmergence_ratelogchange),
                width=0.02,size=0.2,alpha=1) + 
  geom_point(aes(shape=Treatment, color=Treatment)) +
  
  xlab("Change in number of eggs between\nintermediate and initial phenotyping steps")  + 
  ylab("Change in egg-to-adult between\nintermediate and initial phenotyping steps")  +
  xlim(-0.75, 1) + 
  ylim(-1.75, 1.5) +   
  labs(shape = "Test fruit") + 
  scale_shape_manual(values = c(21, 22, 24)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  theme_LO_sober
 Nb_eggsEmergence_rateG7 <- Nb_eggsEmergence_rateG7 + facet_wrap(~ Fruit_s)

 
 
 Nb_eggsEmergence_rateG29 <- ggplot(data = data_logchangeNb_eggsEmergence_rate[data_logchangeNb_eggsEmergence_rate$Generation==29,],
                          aes(x = Nb_eggslogchange,y = Emergence_ratelogchange, group = Treatment, shape = Treatment)) +
  geom_errorbarh(aes(xmin = Nb_eggslogchange-1.96*sdNb_eggslogchange,
                     xmax = Nb_eggslogchange+1.96*sdNb_eggslogchange),
                 height=0.02,size=0.2,alpha=1) +
  geom_errorbar(aes(ymin = Emergence_ratelogchange-1.96*sdEmergence_ratelogchange,
                    ymax = Emergence_ratelogchange+1.96*sdEmergence_ratelogchange),
                width=0.02,size=0.2,alpha=1) + 
  geom_point(aes(shape=Treatment, color=Treatment)) +
  
  xlab("Change in number of eggs between\nfinal and initial phenotyping steps")  + 
  ylab("Change in egg-to-adult viability between\nfinal and initial phenotyping steps")  +
  xlim(-0.75, 1) + 
  ylim(-1.75, 1.5) +   
  labs(shape = "Test fruit", color = "Test fruit") + 
  scale_shape_manual(values = c(21, 22, 24)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  theme_LO_sober
Nb_eggsEmergence_rateG29 <- Nb_eggsEmergence_rateG29 + facet_wrap(~ Fruit_s)
 
legend_trade <- lemon::g_legend(Nb_eggsEmergence_rateG29)

Nb_eggsEmergence_rate <- cowplot::ggdraw() + 
  cowplot::draw_plot(Nb_eggsEmergence_rateG7 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")),
            x = 0, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot(Nb_eggsEmergence_rateG29 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")), 
            x = 0, y = 0, width = 1, height = 0.5) + 
  cowplot::draw_plot_label(c("A", "B"),  
                  x = c(0, 0), y = c(1, 0.5), 
                  size = 14) + 
  cowplot::draw_plot(legend_trade, x = 0.93, y = 0.5, width = 0.001, height = 0.001) 

cowplot::save_plot(file =here::here("figures", "FIG_SX_Nb_eggsEmergence_rate.pdf"),  
                   Nb_eggsEmergence_rate, base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)
```
## Plot Nb_eggs
```{r }
pd <-  position_dodge(width = 0.5)



################### INTERMEDIATE PHENOTYPING

# Re-order levels of Line
data_sum_G7 <- data_logchangeNb_eggs[data_logchangeNb_eggs$Generation == "7",]
data_sum_G7$Line <- factor(data_sum_G7$Line, levels= c("CE2", "CE1", "CE4", "CE3",
                                                       "CR2", "CR3", "CR5", "CR1", "CR4",
                                                       "FR2", "FR3", "FR5", "FR1", "FR4"))

#Plot: 
symp_allop_g7 <- ggplot(data = data_sum_G7, 
                      aes(x = Line, y = logchange, group = Treatment, 
                          color = Fruit_s, shape = Treatment, fill = Fruit_s)) + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey", size = 0.5) + 
  geom_errorbar(aes(ymin = logchange-1.96*sd_logchange, 
                    ymax =logchange + 1.96*sd_logchange, linetype = Line_type),
                  width = 0.2, size = 0.5, alpha = 0.6,position = pd) + 
  geom_point(position = pd, fill = "white", size =3) + 
  ylab("Change in number of eggs between\nintermediate and initial phenotyping steps")  + 
  xlab("Populations") + 
  labs(shape = "Test fruit", color = "Selection fruit") + 
  guides(color = FALSE,
           shape = guide_legend(override.aes = list(fill = c("black")))) + 
  scale_shape_manual(values = c(21, 22, 24)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  theme_LO_sober + theme(axis.text.x  = element_blank()) +
  coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 15),clip = "off") + 
  ggtitle("Intermediate phenotyping step") + 
  annotate("text", x = 2.5, y =1.5, label = 'bold(" Evolved\non cherry")',
                     size =3,colour = "#BC3C6D",parse = TRUE) + 
  annotate("text", x = 7.5, y =1.5, label = 'bold("   Evolved\non cranberry")',
                     size =3,colour = "#FDB424",parse = TRUE) + 
  annotate("text", x = 12.5, y =1.5, label = 'bold("   Evolved\non strawberry")',
                     size =3,colour = "#3FAA96",parse = TRUE)
symp_allop_g7

################### FINAL PHENOTYPING

# Re-order levels of Line
data_sum_G29 <- data_logchangeNb_eggs[data_logchangeNb_eggs$Generation == "29",]
data_sum_G29$Line <- factor(data_sum_G29$Line, levels = c("CEA", "CEB", "CEC", 
                                                          "CRD", "CRA", "CRC", "CRB", "CRE",
                                                          "FRA", "FRC", "FRB"))

symp_allop_G29 <- ggplot(data = data_sum_G29, 
              aes(x = Line, y=logchange, group = Treatment, 
                  color =Fruit_s, shape = Treatment,fill =Fruit_s)) + 
      geom_hline(yintercept = 0, linetype = "dashed", color = "grey", size = 0.5) + 
    geom_point(size =3, position = pd) + 
    geom_errorbar(aes(ymin =logchange-1.96*sd_logchange, ymax =logchange + 1.96*sd_logchange),
                width= 0.2, size = 0.5, alpha = 0.6,position = pd) + 
    ylab("Change in number of eggs between\nfinal and initial phenotyping steps")  + 
    xlab("Populations") + 
    labs(shape = "Test fruit", color = "Selection fruit") + 
    guides(fill = FALSE, alpha = FALSE) + 
    scale_shape_manual(values = c(21, 22, 24)) + 
    scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    theme_LO_sober + theme(axis.text.x  = element_blank()) +
    coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 11),clip = "off") + 
  annotate("text", x = 2, y =1.5, label = 'bold(" Evolved\non cherry")',
                     size =3,colour = "#BC3C6D",parse = TRUE) + 
  annotate("text", x = 6, y =1.5, label = 'bold("   Evolved\non cranberry")',
                     size =3,colour = "#FDB424",parse = TRUE) + 
  annotate("text", x = 10, y =1.5, label = 'bold("   Evolved\non strawberry")',
                     size =3,colour = "#3FAA96",parse = TRUE) + 
  ggtitle("Final phenotyping step") 
symp_allop_G29




### Add stroke
DIF_FITNESS_G7 <- symp_allop_g7 + 
  geom_point(aes(alpha = SA, color = interaction(SA,Fruit_s)), position = pd, size =3, stroke =1.5, fill = "white") + 
  scale_alpha_manual(values = c(0, 1)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96", "#7C2748", "#CA8702", "#328677", "#BC3C6D", "#FDB424", "#3FAA96"))  
DIF_FITNESS_G7

DIF_FITNESS_G29 <- symp_allop_G29 + geom_point(aes(alpha = SA, color = interaction(SA,Fruit_s)), position = pd, size =3, stroke =1.5) + 
      scale_alpha_manual(values = c(0, 1)) + 
      scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96", "#7C2748", "#CA8702", "#328677", "#BC3C6D", "#FDB424", "#3FAA96"))  
DIF_FITNESS_G29


plot_legend <- ggplot(data = data_logchange, aes(x = Line, y=logchange, group = Treatment, 
                  color =Fruit_s, shape = Treatment,fill =Fruit_s)) + 
    geom_point(size =3, position = pd) + 
    labs(shape = "Test fruit", color = "Selection fruit") + 
    scale_shape_manual(values = c(21, 22, 24)) + 
    scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    theme_LO_sober + 
    guides(fill = FALSE) + 
    theme(legend.key.size = unit(0.5, "cm"),
        axis.text.x  = element_blank()) +
    coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 11),clip = "off") 


###########################################################
#############################################ALL PLOT
legend_trade <- lemon::g_legend(plot_legend)
    

SYMP_ALLOP_TOTAL <- cowplot::ggdraw() + 
  cowplot::draw_plot(DIF_FITNESS_G7 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")),
            x = 0, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot(DIF_FITNESS_G29 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")), 
            x = 0, y = 0, width = 1, height = 0.5) + 
  cowplot::draw_plot_label(c("A", "B"),  
                  x = c(0, 0), y = c(1, 0.5), 
                  size = 14) + 
  cowplot::draw_plot(legend_trade, x = 0.93, y = 0.5, width = 0.001, height = 0.001) 

DIF_FITNESS_G7Nb_eggs <- DIF_FITNESS_G7
DIF_FITNESS_G29Nb_eggs <- DIF_FITNESS_G29

cowplot::save_plot(file =here::here("figures", "FIG_SX_HeterogeneityNb_eggs.pdf"),  
                   SYMP_ALLOP_TOTAL, base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)

```

## Plot egg-to-adult viability
```{r }
pd <-  position_dodge(width = 0.5)



################### INTERMEDIATE PHENOTYPING

# Re-order levels of Line
data_sum_G7 <- data_logchangeEmergence_rate[data_logchangeEmergence_rate$Generation == "7",]
data_sum_G7$Line <- factor(data_sum_G7$Line, levels= c("CE2", "CE1", "CE4", "CE3",
                                                       "CR2", "CR3", "CR5", "CR1", "CR4",
                                                       "FR2", "FR3", "FR5", "FR1", "FR4"))

#Plot: 
symp_allop_g7 <- ggplot(data = data_sum_G7, 
                      aes(x = Line, y = logchange, group = Treatment, 
                          color = Fruit_s, shape = Treatment, fill = Fruit_s)) + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey", size = 0.5) + 
  geom_errorbar(aes(ymin = logchange-1.96*sd_logchange, 
                    ymax =logchange + 1.96*sd_logchange, linetype = Line_type),
                  width = 0.2, size = 0.5, alpha = 0.6,position = pd) + 
  geom_point(position = pd, fill = "white", size =3) + 
  ylab("Change in egg-to-adult viability\nbetween intermediate and initial phenotyping steps")  + 
  xlab("Populations") + 
  labs(shape = "Test fruit", color = "Selection fruit") + 
  guides(color = FALSE,
           shape = guide_legend(override.aes = list(fill = c("black")))) + 
  scale_shape_manual(values = c(21, 22, 24)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  theme_LO_sober + theme(axis.text.x  = element_blank()) +
  coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 15),clip = "off") + 
  ggtitle("Intermediate phenotyping step") + 
  annotate("text", x = 2.5, y =1.5, label = 'bold(" Evolved\non cherry")',
                     size =3,colour = "#BC3C6D",parse = TRUE) + 
  annotate("text", x = 7.5, y =1.5, label = 'bold("   Evolved\non cranberry")',
                     size =3,colour = "#FDB424",parse = TRUE) + 
  annotate("text", x = 12.5, y =1.5, label = 'bold("   Evolved\non strawberry")',
                     size =3,colour = "#3FAA96",parse = TRUE)
symp_allop_g7

################### FINAL PHENOTYPING

# Re-order levels of Line
data_sum_G29 <- data_logchangeEmergence_rate[data_logchangeEmergence_rate$Generation == "29",]
data_sum_G29$Line <- factor(data_sum_G29$Line, levels = c("CEA", "CEB", "CEC", 
                                                          "CRD", "CRA", "CRC", "CRB", "CRE",
                                                          "FRA", "FRC", "FRB"))

symp_allop_G29 <- ggplot(data = data_sum_G29, 
              aes(x = Line, y=logchange, group = Treatment, 
                  color =Fruit_s, shape = Treatment,fill =Fruit_s)) + 
      geom_hline(yintercept = 0, linetype = "dashed", color = "grey", size = 0.5) + 
    geom_point(size =3, position = pd) + 
    geom_errorbar(aes(ymin =logchange-1.96*sd_logchange, ymax =logchange + 1.96*sd_logchange),
                width= 0.2, size = 0.5, alpha = 0.6,position = pd) + 
    ylab("Change in egg-to-adult viability\nbetween final and initial phenotyping steps")  + 
    xlab("Populations") + 
    labs(shape = "Test fruit", color = "Selection fruit") + 
    guides(fill = FALSE, alpha = FALSE) + 
    scale_shape_manual(values = c(21, 22, 24)) + 
    scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    scale_fill_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    theme_LO_sober + theme(axis.text.x  = element_blank()) +
    coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 11),clip = "off") + 
  annotate("text", x = 2, y =1.5, label = 'bold(" Evolved\non cherry")',
                     size =3,colour = "#BC3C6D",parse = TRUE) + 
  annotate("text", x = 6, y =1.5, label = 'bold("   Evolved\non cranberry")',
                     size =3,colour = "#FDB424",parse = TRUE) + 
  annotate("text", x = 10, y =1.5, label = 'bold("   Evolved\non strawberry")',
                     size =3,colour = "#3FAA96",parse = TRUE) + 
  ggtitle("Final phenotyping step") 
symp_allop_G29




### Add stroke
DIF_FITNESS_G7 <- symp_allop_g7 + 
  geom_point(aes(alpha = SA, color = interaction(SA,Fruit_s)), position = pd, size =3, stroke =1.5, fill = "white") + 
  scale_alpha_manual(values = c(0, 1)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96", "#7C2748", "#CA8702", "#328677", "#BC3C6D", "#FDB424", "#3FAA96"))  
DIF_FITNESS_G7

DIF_FITNESS_G29 <- symp_allop_G29 + geom_point(aes(alpha = SA, color = interaction(SA,Fruit_s)), position = pd, size =3, stroke =1.5) + 
      scale_alpha_manual(values = c(0, 1)) + 
      scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96", "#7C2748", "#CA8702", "#328677", "#BC3C6D", "#FDB424", "#3FAA96"))  
DIF_FITNESS_G29


plot_legend <- ggplot(data = data_logchange, aes(x = Line, y=logchange, group = Treatment, 
                  color =Fruit_s, shape = Treatment,fill =Fruit_s)) + 
    geom_point(size =3, position = pd) + 
    labs(shape = "Test fruit", color = "Selection fruit") + 
    scale_shape_manual(values = c(21, 22, 24)) + 
    scale_color_manual(values = c("#BC3C6D", "#FDB424", "#3FAA96")) + 
    theme_LO_sober + 
    guides(fill = FALSE) + 
    theme(legend.key.size = unit(0.5, "cm"),
        axis.text.x  = element_blank()) +
    coord_cartesian(expand = FALSE, ylim = c(-2, 2), xlim=c(0, 11),clip = "off") 


###########################################################
#############################################ALL PLOT
legend_trade <- lemon::g_legend(plot_legend)
    

SYMP_ALLOP_TOTAL <- cowplot::ggdraw() + 
  cowplot::draw_plot(DIF_FITNESS_G7 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")),
            x = 0, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot(DIF_FITNESS_G29 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")), 
            x = 0, y = 0, width = 1, height = 0.5) + 
  cowplot::draw_plot_label(c("A", "B"),  
                  x = c(0, 0), y = c(1, 0.5), 
                  size = 14) + 
  cowplot::draw_plot(legend_trade, x = 0.93, y = 0.5, width = 0.001, height = 0.001) 

SYMP_ALLOP_TOTAL


cowplot::save_plot(file =here::here("figures", "FIG_SX_HeterogeneityEgg-to-adultviability.pdf"),  
                   SYMP_ALLOP_TOTAL, base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)



SYMP_ALLOP_TOTAL <- cowplot::ggdraw() + 
  cowplot::draw_plot(DIF_FITNESS_G7Nb_eggs + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")),
            x = 0, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot(DIF_FITNESS_G29Nb_eggs + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")), 
            x = 0, y = 0, width = 1, height = 0.5) + 
  cowplot::draw_plot(DIF_FITNESS_G7 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")),
            x = 0.5, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot(DIF_FITNESS_G29 + theme(legend.position = 'none', 
                             plot.margin =unit(c(0.5, 3.5, 0.5, 0.5), "cm")), 
            x = 0.5, y = 0, width = 1, height = 0.5) + 
  cowplot::draw_plot_label(c("A", "B", "C", "D"),  
                  x = c(0, 0, 0.5, 0.5), y = c(1, 0.5, 1, 0.5), 
                  size = 14) + 
  cowplot::draw_plot(legend_trade, x = 0.93, y = 0.5, width = 0.001, height = 0.001) 

cowplot::save_plot(file =here::here("figures", "FIG_SX_HeterogeneityNb_Egges_Egg-to-adultviability.pdf"),  
                   SYMP_ALLOP_TOTAL, base_height = 20/cm(1), base_width = 30/cm(1), dpi = 1200)

```




# SUP: Long vs Fitness
## Data
```{r }
#To consider fruit maternal effect and GF maternal effect: new plot 
## Y-axis = log change = log(Fitness pheno)-log(fitness initial)
## X-axis = fitness temp / fitness initial
 ## example: for CEA during first phase 
    ## log(mean (CE1 from G2 to G5) / mean (Cherry G2))

##To check with Nico: for x-axis: denominator=mean Cherry G2 or mean CE1 G2 (???????????)


####### Phenotyping steps 
#Compute log change
data_logchange <- computelogchange(fitness_dataset_intermediate = data_G7, fitness_dataset_final = data_G29)

#Remove allopatric data
data_fitness_pheno <- data_logchange[data_logchange$SA==1,]
data_fitness_pheno <- data_fitness_pheno[, c("Line", "Fruit_s", "logchange", "sd_logchange")]


####### Longitudinal data 
#Compute log change
data_logchange_long <- computelogchange_forlongdata(longitudinal_dataset = data_sum)


####### Merge data
data_compare_longitudinal_pheno <- merge(data_logchange_long,data_fitness_pheno,by=c("Line", "Fruit_s"))
data_compare_longitudinal_pheno <- droplevels(data_compare_longitudinal_pheno)

## Does not seem to be a correlation between measures
cor.test(data_compare_longitudinal_pheno$logchange[data_compare_longitudinal_pheno$Phase=="first_prepool"], data_compare_longitudinal_pheno$logchange_long[data_compare_longitudinal_pheno$Phase=="first_prepool"])

cor.test(data_compare_longitudinal_pheno$logchange[data_compare_longitudinal_pheno$Phase=="second_postpool"], data_compare_longitudinal_pheno$logchange_long[data_compare_longitudinal_pheno$Phase=="second_postpool"])


####### Geary test
#Lines: CE2 and CR2 do not pass Geary's test (the threshold of a standardized mean greater than 3)
data_compare_longitudinal_pheno$Line_type  <- ifelse(data_compare_longitudinal_pheno$Line == "CR2"|
                                                       data_compare_longitudinal_pheno$Line == "CE2", "solid","dashed")

```


## Plot long vs fitness
```{r }
PLOT_IntermediatePheno_LOGCHANGE<-ggplot(data=data_compare_longitudinal_pheno[data_compare_longitudinal_pheno$Phase=="first_prepool",], 
       aes(y=logchange,x=logchange_long, color=Fruit_s,shape=Fruit_s, linetype=Line_type)) +
  geom_errorbar(aes(x = logchange_long, 
                    ymin = logchange-(1.96*sd_logchange), 
                    ymax = logchange+(1.96*sd_logchange)),
                  width=0.02,size=0.2,alpha=1) +
  geom_errorbarh(aes(y = logchange, 
                    xmin = logchange_long-1.96*sd_logchange_long,
                    xmax = logchange_long+1.96*sd_logchange_long),
                 height=0.02,size=0.2,alpha=1) +
  geom_point(size=3, fill = "#ffffff", stroke=1.3) +
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_shape_manual(values=c(21, 22, 24)) + 
  xlab("Fitness change between average fitness across generations 2 to 5\nand average fitness across generations 2 to 5") + 
  ylab("Fitness change between\nintermediate and initial phenotyping steps") + 
  labs(color="Selection fruit", shape="Selection fruit") + 
  geom_abline(intercept = 0, slope = 1, color="black", linetype="dashed", size=0.8) +
  ylim(-1.9,0.9) + 
  xlim(-1.9,0.9) +
  guides(linetype=FALSE) +
  ggtitle("Intermediate phenotyping step vs. Phase 1") +
  theme_LO_sober 
PLOT_IntermediatePheno_LOGCHANGE 


PLOT_FinalPheno_LOGCHANGE <- 
  ggplot(data=data_compare_longitudinal_pheno
                        [data_compare_longitudinal_pheno$Phase=="second_postpool",], 
                        aes(y=logchange, x=logchange_long, 
                            color=Fruit_s, shape=Fruit_s, fill=Fruit_s, linetype=Line_type)) +
  geom_errorbar(aes(x = logchange_long, 
                    ymin = logchange-(1.96*sd_logchange),
                    ymax = logchange+(1.96*sd_logchange)),
                  width=0.02,size=0.2,alpha=1) +
  geom_errorbarh(aes(y = logchange, 
                    xmin = logchange_long-1.96*sd_logchange_long,
                    xmax = logchange_long+1.96*sd_logchange_long),
                 height=0.02,size=0.2,alpha=1) +
  geom_abline(intercept = 0, slope = 1, color="black", 
                 linetype="dashed", size=0.8) +
  geom_point(size=3, stroke=1) +
  scale_fill_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_shape_manual(values=c(21, 22, 24)) + 
  xlab("Fitness change between average fitness across generations 13 to 26\nand average fitness across generations 2 to 5") + 
  ylab("Fitness change between\nfinal and initial phenotyping steps") + 
  labs(color="Selection fruit", shape="Selection fruit", fill="Selection fruit") + 
  ylim(-0.5,1.7) +
  xlim(-0.5,1.7) +
  guides(linetype=FALSE) +
  ggtitle("Final phenotyping step vs. Phase 3") +
  theme_LO_sober
PLOT_FinalPheno_LOGCHANGE  


    

PLOT_Comparison_Pheno_Longitudinal_LOGCHANGE <- cowplot::ggdraw() +
  cowplot::draw_plot(PLOT_IntermediatePheno_LOGCHANGE + 
                       theme(axis.title.y = element_text(size=10),
                             axis.title.x = element_text(size=10)),
            x = 0, y = 0.5, width = 1, height = 0.5) +
  cowplot::draw_plot(PLOT_FinalPheno_LOGCHANGE + 
                       theme(axis.title.y = element_text(size=10),
                             axis.title.x = element_text(size=10)),
            x =0, y = 0, width = 1, height = 0.5) +
  cowplot::draw_plot_label(c("A", "B"),  
                  x = c(0,0), y = c(1,0.5), 
                  size = 14) 
PLOT_Comparison_Pheno_Longitudinal_LOGCHANGE


cowplot::save_plot(file=here::here("figures", "SUPMAT_LogChange_Pheno_Longitudinal.pdf"),
                   PLOT_Comparison_Pheno_Longitudinal_LOGCHANGE, base_height = 20/cm(1), base_width = 15/cm(1), dpi = 1200)

```




## Extra plot Maternal effects
```{r }

m <- lm(logchange ~ logchange_long + offset(logchange_long),
        data = data_compare_longitudinal_pheno[data_compare_longitudinal_pheno$Phase=="second_postpool",]) 

summary(m)
#pval of logchange_long = 0.003 => slope is different of 1 
#pval of Intercept = 0.80 => no evolution of maternal effect?


## Ratio maternal effects derived pop / maternal effect ancestral population 
exp(coef(m)[1]) 

# proportion of adaptation due to maternal effects
data_compare_longitudinal_pheno$mateff <- (data_compare_longitudinal_pheno$logchange_long -
  data_compare_longitudinal_pheno$logchange) / data_compare_longitudinal_pheno$logchange_long

data_compare_longitudinal_pheno


#Plot
PLOT_Maternaleffects<-ggplot(data=data_compare_longitudinal_pheno, 
       aes(y=mateff,x=logchange_long, color=Fruit_s, shape=Fruit_s, fill=interaction(Phase,Fruit_s))) +
  geom_point(size=3,  stroke=1.3) +
  scale_fill_manual(name = "Phase", 
                      values = c("#ffffff","#BC3C6D", "#ffffff","#FDB424", "#ffffff", "#3FAA96"), 
                      breaks = c("first_prepool.Cherry", "second_postpool.Cherry"), 
                      labels = c("Phase 1","Phase 3")) +
  scale_color_manual(values=c("#BC3C6D", "#FDB424", "#3FAA96")) + 
  scale_shape_manual(values=c(21, 22, 24)) + 
  xlab("Fitness change between average fitness\nacross generations 2 to 5 (13 to 26) and generation 2") + 
  ylab("Proportion of adaptation\ndue to evolution of maternal effects") + 
  labs(color="Selection fruit", shape="Selection fruit") + 
  guides(fill = guide_legend(override.aes = list(fill = c("white","black"), shape=21))) +
  theme_LO_sober 
PLOT_Maternaleffects 


cowplot::save_plot(file=here::here("figures", "SUPMAT_Maternal_effects.pdf"),
                   PLOT_Maternaleffects, base_height = 20/cm(1), base_width = 15/cm(1), dpi = 1200)


```



# SUP: Adaptation 
## Analysis Phase 1 (8 fruits)
```{r }

## Check random effect structure
mod1 <- lme4::lmer(fitness ~ Line*Generation + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN, REML = TRUE)
mod2 <- lme4::lmer(fitness ~ Line*Generation + (1|Generation) + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN, REML = TRUE)
MuMIn::model.sel(mod1, mod2)

##Cl: the model with the same generation effect across lines does not increase the likelihood and does not provide a better fit to the data

#Models
mod_all_interaction <- lme4::lmer(fitness ~ Fruit_s*Generation + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

mod_all_generation <- lme4::lmer(fitness ~ Generation + (1|Generation:Fruit_s) , 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

mod_all_fruit_generation <- lme4::lmer(fitness ~ Fruit_s+Generation + (1|Generation:Fruit_s) , 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

mod_all_fruit <- lme4::lmer(fitness ~ Fruit_s + (1|Generation:Fruit_s) , 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

mod_all_line <- lme4::lmer(fitness ~ Line + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

mod_all_null <- lme4::lmer(fitness ~ 1  + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

mod_all_interaction_line_generation <- lme4::lmer(fitness ~ Line*Generation + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

mod_line_generation <- lme4::lmer(fitness ~ Line+Generation + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN, REML = FALSE)

MuMIn::model.sel(mod_all_interaction,mod_all_fruit_generation,mod_all_fruit,mod_all_null,mod_all_generation,mod_all_line,mod_all_interaction_line_generation,mod_line_generation)

summary(mod_all_interaction)







#Posthoc
mod_all_interaction <- lme4::lmer(fitness ~ Fruit_s*Generation + (1|Generation) + (1|Generation:Fruit_s), 
            weights = N, data = data_sum_allfruits_AN)
summary(mod_all_interaction)

emt1 <- emmeans::emtrends(mod_all_interaction, "Fruit_s", var = "Generation")
emt1          ### estimated slopes of Generation for each level of Fruit_s
pairs(emt1)   ### comparison of slopes



```




## Plot Phase 1 (8 fruits)
```{r }

pd <- position_dodge(0.3) # move them .05 to the left and right

#Extract slope and intercept
dat_8fruits <- expand.grid(Generation=as.numeric(levels(as.factor(data_sum_allfruits_AN$Generation))),
                           Fruit_s=unique(data_sum_allfruits_AN$Fruit_s))
dat_8fruits$fitness_predicted <- predict(mod_all_interaction, newdata = dat_8fruits, 
                          re.form= NA, type = "response")





PLOT_CHERRY <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Cherry",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Cherry",],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white",stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  ylab("Fitness") + 
  xlab("Generation") + 
  xlim("1","2","3","4","5") +
  scale_color_manual(values = c("black", "#BC3C6D")) + 
  ggtitle("Cherry") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#BC3C6D"))
PLOT_CHERRY



PLOT_CRANBERRY <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Cranberry",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Cranberry",],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white",stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  ylab("Fitness") + 
  xlim("1","2","3","4","5") +
  xlab("Generation") + 
  scale_color_manual(values = c("black","#FDB424")) + 
  ggtitle("Cranberry") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#FDB424"))
PLOT_CRANBERRY


PLOT_STRAWBERRY <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Strawberry",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Strawberry",],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white",stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  xlim("1","2","3","4","5") +
  ylab("Fitness") + 
  xlab("Generation") + 
  scale_color_manual(values = c("black","#3FAA96")) + 
  ggtitle("Strawberry") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#3FAA96"))
PLOT_STRAWBERRY



PLOT_GRAPE <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Grape",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Grape"&dat_8fruits$Generation == c(2,3),],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white",stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  xlim("1","2","3","4","5") +
  ylab("Fitness") + 
  xlab("Generation") + 
  scale_color_manual(values = c("black","#7B7554")) + 
  ggtitle("Grape") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#7B7554"))
PLOT_GRAPE

PLOT_ROSEHIPS <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Rosehips",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Rosehips"&dat_8fruits$Generation != 5,],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white",stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  xlim("1","2","3","4","5") +
  ylab("Fitness") + 
  xlab("Generation") + 
  scale_color_manual(values = c("black","#8ACDEA")) + 
  ggtitle("Rose hips") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#8ACDEA"))
PLOT_ROSEHIPS



PLOT_TOMATO <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Tomato",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Tomato"&dat_8fruits$Generation != 5,],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white", stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  xlim("1","2","3","4","5") +
  ylab("Fitness") + 
  xlab("Generation") + 
  scale_color_manual(values = c( "black","#ED6F47")) + 
  ggtitle("Tomato") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#ED6F47"))
PLOT_TOMATO


PLOT_FIG <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Fig",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Fig"&dat_8fruits$Generation != 5,],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white", stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  xlim("1","2","3","4","5") +
  ylab("Fitness") + 
  xlab("Generation") + 
  scale_color_manual(values = c("black","#93194F")) + 
  ggtitle("Fig") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#93194F"))
PLOT_FIG


PLOT_BLACKCURRANT <- ggplot(data = data_sum_allfruits[data_sum_allfruits$Fruit_s == "Blackcurrant",], 
                            aes(x = factor(Generation), group = Line, y = fitness, colour =Fruit_s)) + 
  geom_errorbar(aes(ymin = fitness-1.96*se_fitness, ymax = fitness + 1.96*se_fitness),
                width=.1,position = pd, size = 0.4,color = "black") + 
  geom_line(size = 0.5,position = pd) + 
  geom_line(data = dat_8fruits[dat_8fruits$Fruit_s == "Blackcurrant"&dat_8fruits$Generation == c(2,3),],
                     aes(x = factor(Generation), y = fitness_predicted, colour = "black", group=NA), size = 0.7) +
  geom_point(size = 2, position = pd, shape = 21, fill = "white", stroke = 1.2) + 
  ylim(-5.65, 1.25) +
  xlim("1","2","3","4","5") +
  ylab("Fitness") + 
  xlab("Generation") + 
  scale_color_manual(values = c( "black","#203753")) + 
  ggtitle("Blackcurrant") + 
  theme_LO_adaptation + theme(plot.title = element_text(color = "#203753"))
PLOT_BLACKCURRANT


DYNAMIC_EIGHT_JOIN <- cowplot::ggdraw() + 
  cowplot::draw_plot(PLOT_STRAWBERRY, x = 0, y = 0, width = 0.5, height = 0.28) + 
  cowplot::draw_plot(PLOT_GRAPE+ theme(axis.title.x = element_blank(),
                                              axis.text.x = element_blank(),
                                              axis.ticks.x = element_blank(),
                                              axis.line.x = element_blank()),
                     x = 0, y = 0.28, width = 0.5, height = 0.23) + 
  cowplot::draw_plot(PLOT_CRANBERRY+ theme(axis.title.x = element_blank(),
                                              axis.text.x = element_blank(),
                                              axis.ticks.x = element_blank(),
                                              axis.line.x = element_blank()),
                     x = 0, y = 0.53, width = 0.5, height = 0.23) + 
  cowplot::draw_plot(PLOT_BLACKCURRANT+ theme(axis.title.x = element_blank(),
                                              axis.text.x = element_blank(),
                                              axis.ticks.x = element_blank(),
                                              axis.line.x = element_blank()),
                     x = 0, y = 0.77, width = 0.5, height = 0.23) + 
  cowplot::draw_plot(PLOT_TOMATO+ theme(axis.title.y = element_blank()), 
                     x = 0.5, y = 0, width = 0.5, height = 0.28) + 
  cowplot::draw_plot(PLOT_ROSEHIPS+ theme(axis.title.y = element_blank(),
                                              axis.title.x = element_blank(),
                                              axis.text.x = element_blank(),
                                              axis.ticks.x = element_blank(),
                                              axis.line.x = element_blank()),
                     x = 0.5, y = 0.28, width = 0.5, height = 0.23) + 
  cowplot::draw_plot(PLOT_FIG+ theme(axis.title.y = element_blank(),
                                              axis.title.x = element_blank(),
                                              axis.text.x = element_blank(),
                                              axis.ticks.x = element_blank(),
                                              axis.line.x = element_blank()),
                     x = 0.5, y = 0.53, width = 0.5, height = 0.23) + 
  cowplot::draw_plot(PLOT_CHERRY + theme(axis.title.y = element_blank(),
                                              axis.title.x = element_blank(),
                                              axis.text.x = element_blank(),
                                              axis.ticks.x = element_blank(),
                                              axis.line.x = element_blank()),
                     x = 0.5, y = 0.77, width = 0.5, height = 0.23) +
  cowplot::draw_plot_label(c("A", "C",  "E", "G", "B",  "D", "F",  "H"),  
                  x = c(0, 0, 0, 0, 0.5, 0.5, 0.5, 0.5), 
                  y = c(1, 0.75, 0.50, 0.27, 1, 0.75, 0.5, 0.27), 
                  hjust = c(-0.5, -0.5, -0.5,-0.5, -0.5, -0.5, -0.5, -0.5), 
                  vjust = c(1.5, 1.5, 1.5,1.5, 1.5, 1.5,1.5, 1.5),
                  size = 12) 
 DYNAMIC_EIGHT_JOIN



cowplot::save_plot(file =here::here("figures", "SUPMAT_Fitness8Fruits.pdf"), DYNAMIC_EIGHT_JOIN, base_height = 17/cm(1), base_width = 15/cm(1), dpi = 1200)



```





## Analysis PHASE 3    
```{r }


################### PHASE 3



## Test for random effects
mod0 <- lme4::lmer(fitness~ Generation*Line + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = TRUE)
mod1 <- lme4::lmer(fitness~ Generation*Line + (1|Generation) + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = TRUE)
MuMIn::model.sel(mod0, mod1)

## Cl: only a very slight increase in likelihood when adding the second random effect

## Test for fixed effects
mod1 <- lme4::lmer(fitness ~ 1 + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE) 
mod2 <- lme4::lmer(fitness~ Line  + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE)
mod3 <- lme4::lmer(fitness ~ Fruit_s  + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE) 
mod4 <- lme4::lmer(fitness~ Generation*Line + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE)
mod5 <- lme4::lmer(fitness~ Generation+Line + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE)
mod6 <- lme4::lmer(fitness ~ Generation*Fruit_s + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE) 
mod7 <- lme4::lmer(fitness ~ Generation+Fruit_s + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE) 
mod8 <- lme4::lmer(fitness ~ Generation + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",], REML = FALSE) 


anova(mod1,mod2)
MuMIn::model.sel(mod1,mod2,mod3,mod4,mod5,mod6, mod7, mod8)



mod3 <- lme4::lmer(fitness ~ Fruit_s-1 + (1|Generation) + (1|Generation:Fruit_s), 
            weights = N, data = data_sum[data_sum$Phase=="second_postpool",]) 

summary(mod3)
```




# SUP: Pooling effect
## Data
```{r }

########### Hypothesis 1 
#Hypothesis 1: effect of pool 
#Take the mean of all populations for each selection fruit 
 
CheCran_hypo1 <- computelogchange_POOL_hypo1(data_G7, "Cherry", "Cranberry")



########### Hypothesis 2 
#Hypothesis 2: effect of pool 
#Take the fitness change of the population with the highest fitness in G7 
TEMP_dataG7_CheCran <- formattinglogchange(data_logchange, "7", "Cherry", "Cranberry")
fittest_lines<-computelogchange_POOL_hypo2(data_G7, "Cherry", "Cranberry")
CheCran_hypo2<-TEMP_dataG7_CheCran[TEMP_dataG7_CheCran$Line==fittest_lines,]




```

## Plot
```{r }
#Initial plot from main text
ymin = -50
ymax = 50


pd <- position_dodge(0.3) # move them .05 to the left and right

# Limits
ymin_CheCranG29=min(min(TEMP_dataG29_CheCran$logchange_allop-1.96*TEMP_dataG29_CheCran$sd_allop, na.rm= TRUE),
                min(TEMP_dataG29_CheCran$logchange_symp-1.96*TEMP_dataG29_CheCran$sd_symp, na.rm= TRUE))
ymax_CheCranG29=max(max(TEMP_dataG29_CheCran$logchange_allop + 1.96*TEMP_dataG29_CheCran$sd_allop, na.rm= TRUE),
                max(TEMP_dataG29_CheCran$logchange_symp + 1.96*TEMP_dataG29_CheCran$sd_symp, na.rm= TRUE))


CheCran_G29 <- ggplot(data = TEMP_dataG29_CheCran) + 
  geom_errorbar(aes(x =logchange_symp, ymin = logchange_allop-(1.96*sd_allop), 
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp),
                  width= 0.02, size = 0.3, alpha = 0.8) + 
  geom_errorbarh(aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp),
                 height = 0.02, size = 0.3, alpha = 0.8) + 
  geom_point(aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size =3, fill = "white", stroke =1.2) + 
  xlab("Fitness change in\nselective environment")  + 
  ylab("Fitness change in\nalternative environment")  + 
  ggtitle("Cherry vs. Cranberry") + 
  labs(shape = "Test fruit", color = "Evolution fruit") + 
  scale_shape_manual(values = c(16, 15)) + 
  scale_color_manual(values = c("#BC3C6D", "#FDB424"))  + 
  coord_cartesian(ylim = c(ymin_CheCranG29, ymax_CheCranG29), 
                  xlim = c(ymin_CheCranG29, ymax_CheCranG29)) + 
  theme_LO_sober
 CheCran_G29
 
 
 
 

PLOT_HYPO_1<-CheCran_G29 +  
  geom_errorbar(data = CheCran_hypo1, aes(x =logchange_symp, ymin = logchange_allop-(1.96*sd_allop), 
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp),
                  width= 0.02, size = 0.2, alpha =1) + 
  geom_errorbarh(data = CheCran_hypo1, 
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp),
                 height = 0.02, size = 0.2, alpha =1) + 
  geom_point(data = CheCran_hypo1,
             aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size = 6, fill = "white", stroke = 2) +
    geom_point(data = CheCran_hypo1,
             aes(x =logchange_symp, y = logchange_allop,  fill = Symp, shape = Allop),
                 size = 3, fill = "white", color = "white", stroke = 2) +
  ggtitle("Hypothesis 1: Mean of populations effect")
PLOT_HYPO_1



PLOT_HYPO_2<-CheCran_G29 +  
  geom_errorbar(data = CheCran_hypo2, aes(x = logchange_symp, 
                                          ymin = logchange_allop-(1.96*sd_allop), 
                    ymax = logchange_allop + (1.96*sd_allop),
                    color = Symp),
                  width= 0.02, size = 0.2, alpha =1) + 
  geom_errorbarh(data = CheCran_hypo2, 
                 aes(y = logchange_allop, xmin = logchange_symp-1.96*sd_symp, xmax = logchange_symp + 1.96*sd_symp, 
                 color = Symp),
                 height = 0.02, size = 0.2, alpha =1) + 
  geom_point(data = CheCran_hypo2,
             aes(x =logchange_symp, y = logchange_allop,  color = Symp,fill = Symp, shape = Allop),
                 size = 6, fill = "white", stroke = 2) +
    geom_point(data = CheCran_hypo2,
             aes(x = logchange_symp, y = logchange_allop,  fill = Symp, shape = Allop),
                 size = 3, fill = "white", color = "white", stroke = 2) +
  ggtitle("Hypothesis 2: Fittest population effect")
PLOT_HYPO_2






#legend1
legend_tradevide<- ggplot(CheCran_hypo2, aes(x=logchange_symp, y=logchange_allop, group=Fruit_s, colour=Fruit_s)) +
  geom_point(size=1.5, position=pd, fill="white", alpha=0.6) + 
  geom_errorbar(aes(ymin=logchange_allop-(1.96*sd_allop), ymax=logchange_allop+(1.96*sd_allop),),
                  width=0.4,size=0.4, alpha=0.3) +
  labs(colour = "Population \nevolved on:") + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424","#3FAA96"), 
                     label=c("Cherry","Cranberry", "Strawberry")) +   
  theme_LO_sober +
  theme(legend.title = element_text(colour="black", size=10, face="bold"), 
          legend.text = element_text(colour="black", size=8))

legend_tradevide<-lemon::g_legend(legend_tradevide)

 #legend hypo 1
legend_hypo1<- ggplot(CheCran_hypo2, aes(x=logchange_symp, y=logchange_allop, group=Fruit_s, colour=Fruit_s)) +
  geom_point(size=1.5, position=pd, fill="white", alpha=0.6) + 
  geom_errorbar(aes(ymin=logchange_allop-(1.96*sd_allop), ymax=logchange_allop+(1.96*sd_allop),),
                  width=0.4,size=0.4, alpha=0.3) +
  labs(colour = "Mean of population\nevolved on:") + 
  geom_point(size=2, shape=21, fill="white", stroke = 2) + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424","#3FAA96"), 
                     label=c("Cherry","Cranberry", "Strawberry")) +   
  theme_LO_sober +
  theme(legend.title = element_text(colour="black", size=10, face="bold"), 
          legend.text = element_text(colour="black", size=8))

extract_legend_hypo1<-lemon::g_legend(legend_hypo1)

 #legend2
legend_hypo2<- ggplot(CheCran_hypo2, aes(x=logchange_symp, y=logchange_allop, group=Fruit_s, colour=Fruit_s)) +
  geom_point(size=1.5, position=pd, fill="white", alpha=0.6) + 
  geom_errorbar(aes(ymin=logchange_allop-(1.96*sd_allop), ymax=logchange_allop+(1.96*sd_allop),),
                  width=0.4,size=0.4, alpha=0.3) +
  labs(colour = "Population with \nthe highest fitness \non each selection fruit:") + 
  geom_point(size=2, shape=21, fill="white", stroke = 2) + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424","#3FAA96"), 
                     label=c("Cherry","Cranberry", "Strawberry")) +   
  theme_LO_sober +
  theme(legend.title = element_text(colour="black", size=10, face="bold"), 
          legend.text = element_text(colour="black", size=8))

extract_legend_hypo2<-lemon::g_legend(legend_hypo2)



ERRORCROSSES_G7_HYPO1_2 <- cowplot::ggdraw() +
  cowplot::draw_plot(PLOT_HYPO_1+theme(legend.position = "none"), 
            x =0.00, y = 0.5, width = 0.75, height = 0.5) +
  cowplot::draw_plot(PLOT_HYPO_2+theme(legend.position = "none"), 
            x = 0.0, y = 0, width = 0.75, height = 0.5) +
  cowplot::draw_plot(legend_tradevide, x = 0.78, y = 0.85, width = 0.1, height = 0.1) +
  cowplot::draw_plot(extract_legend_hypo1, x = 0.82, y = 0.7, width = 0.1, height = 0.1) +
  cowplot::draw_plot(legend_tradevide, x = 0.76, y = 0.35, width = 0.1, height = 0.1) +
  cowplot::draw_plot(extract_legend_hypo2, x = 0.82, y = 0.2, width = 0.1, height = 0.1) 
ERRORCROSSES_G7_HYPO1_2





ERRORCROSSES_G7_HYPO1 <- cowplot::ggdraw() +
  cowplot::draw_plot(PLOT_HYPO_1+theme(legend.position = "none", 
                                       plot.title = element_blank()), 
            x =0.00, y = 0, width = 0.75, height = 1) +
  cowplot::draw_plot(legend_tradevide, x = 0.78, y = 0.3, width = 0.1, height = 0.1) +
  cowplot::draw_plot(extract_legend_hypo1, x = 0.82, y = 0.55, width = 0.1, height = 0.1)
ERRORCROSSES_G7_HYPO1

ERRORCROSSES_G7_HYPO2 <- cowplot::ggdraw() +
  cowplot::draw_plot(PLOT_HYPO_2+theme(legend.position = "none", 
                                       plot.title = element_blank()), 
            x =0.00, y = 0, width = 0.75, height = 1) +
  cowplot::draw_plot(legend_tradevide, x = 0.76, y = 0.3, width = 0.1, height = 0.1) +
  cowplot::draw_plot(extract_legend_hypo2, x = 0.82, y = 0.55, width = 0.1, height = 0.1)
ERRORCROSSES_G7_HYPO2




# 
# cowplot::save_plot(file =here::here("figures", "SUPMAT_Pooleffect_Hypothesis.pdf"),
#                    ERRORCROSSES_G7_HYPO1_2,
#                    base_height = 18/cm(1), base_width = 15/cm(1), dpi = 610)
# 
# 

cowplot::save_plot(file =here::here("figures", "SUPMAT_Pooleffect_Hypothesis1.pdf"),
                   ERRORCROSSES_G7_HYPO1,
                   base_height = 12/cm(1), base_width = 15/cm(1), dpi = 610)


cowplot::save_plot(file =here::here("figures", "SUPMAT_Pooleffect_Hypothesis2.pdf"),
                   ERRORCROSSES_G7_HYPO2,
                   base_height = 12/cm(1), base_width = 15/cm(1), dpi = 610)







```








## Extra plot
```{r } 
PAIR_StrawChe_G29
PAIR_CranStraw_G29
PAIR_CheCran_G29


## Data
# EC_Cran_Cher_G7<-formattingplotpair(data_logchange, "7", "Cherry", "Cranberry")
# EC_Straw_Cran_G7<-formattingplotpair(data_logchange, "7", "Cranberry", "Strawberry")
# EC_Straw_Cher_G7<-formattingplotpair(data_logchange, "7", "Strawberry", "Cherry")

########### Hypothesis 1 
#Hypothesis 1: effect of pool 
#Take the mean of all populations for each selection fruit 
dataset_hypo1 <- formatting_POOL_hypo1(fitness_dataset_intermediate = data_G7)

########### Hypothesis 2 
#Hypothesis 2: effect of pool 
#Take the fitness change of the population with the highest fitness in G7 
fittest_lines<-formatting_POOL_hypo2(data_G7)
EC_Cran_Cher_hypo2<-EC_Cran_Cher_G7[EC_Cran_Cher_G7$Line == fittest_lines[1]|
                                      EC_Cran_Cher_G7$Line == fittest_lines[2]|
                                      EC_Cran_Cher_G7$Line == fittest_lines[3],]
EC_Straw_Cran_hypo2<-EC_Straw_Cran_G7[EC_Straw_Cran_G7$Line == fittest_lines[1]|
                                       EC_Straw_Cran_G7$Line == fittest_lines[2]|
                                        EC_Straw_Cran_G7$Line == fittest_lines[3],]
EC_Straw_Cher_hypo2<-EC_Straw_Cher_G7[EC_Straw_Cher_G7$Line == fittest_lines[1]|
                                       EC_Straw_Cher_G7$Line == fittest_lines[2]|
                                        EC_Straw_Cher_G7$Line == fittest_lines[3],]


PAIR_CheCran_G29_HYPO_1 <- PAIR_CheCran_G29 +
  geom_errorbar(data = dataset_hypo1, 
                aes(x=logchange_Strawberry, 
                    ymin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                    ymax = logchange_Cranberry+1.96*sd_logchange_Cranberry, Line=NA),
                width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(data = dataset_hypo1, 
                 aes(y=logchange_Cranberry, 
                     xmin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                     xmax = logchange_Strawberry+1.96*sd_logchange_Strawberry),
                 height=0.02, size=0.2, alpha=1) + 
  geom_point(data = dataset_hypo1, 
             aes(x = logchange_Strawberry, y = logchange_Cranberry), 
             shape=21, size=4,  fill = "#ffffff", stroke=1.5)
PAIR_CheCran_G29_HYPO_1


PAIR_StrawChe_G29_HYPO_1<-PAIR_StrawChe_G29 +
  geom_errorbar(data = dataset_hypo1, 
                aes(x=logchange_Strawberry, 
                    ymin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                    ymax = logchange_Cranberry+1.96*sd_logchange_Cranberry, Line=NA),
                width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(data = dataset_hypo1, 
                 aes(y=logchange_Cranberry, 
                     xmin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                     xmax = logchange_Strawberry+1.96*sd_logchange_Strawberry),
                 height=0.02, size=0.2, alpha=1) + 
  geom_point(data = dataset_hypo1, 
             aes(x = logchange_Strawberry, y = logchange_Cranberry), 
             shape=21, size=4,  fill = "#ffffff", stroke=1.5)
PAIR_StrawChe_G29_HYPO_1


PAIR_CranStraw_G29_HYPO_1<-PAIR_StrawChe_G29  + 
  geom_errorbar(data = dataset_hypo1, 
                aes(x=logchange_Strawberry, 
                    ymin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                    ymax = logchange_Cranberry+1.96*sd_logchange_Cranberry, Line=NA),
                width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(data = dataset_hypo1, 
                 aes(y=logchange_Cranberry, 
                     xmin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                     xmax = logchange_Strawberry+1.96*sd_logchange_Strawberry),
                 height=0.02, size=0.2, alpha=1) + 
  geom_point(data = dataset_hypo1, 
             aes(x = logchange_Strawberry, y = logchange_Cranberry), 
             shape=21, size=4,  fill = "#ffffff", stroke=1.5)
PAIR_CranStraw_G29_HYPO_1
 












PAIR_CranStraw_G29_HYPO_2 <- PAIR_CranStraw_G29 +
  geom_errorbar(data = EC_Straw_Cran_hypo2, 
                aes(x=logchange_Strawberry, 
                    ymin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                    ymax = logchange_Cranberry+1.96*sd_logchange_Cranberry),
                width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(data = EC_Straw_Cran_hypo2, 
                 aes(y=logchange_Cranberry, 
                     xmin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                     xmax = logchange_Strawberry+1.96*sd_logchange_Strawberry),
                 height=0.02, size=0.2, alpha=1) + 
  geom_point(data = EC_Straw_Cran_hypo2, 
             aes(x = logchange_Strawberry, y = logchange_Cranberry), 
             shape=21, size=4,  fill = "#ffffff", stroke=1.5)
PAIR_CranStraw_G29_HYPO_2



PAIR_StrawChe_G29_HYPO_2 <- PAIR_StrawChe_G29 +
  geom_errorbar(data = EC_Straw_Cher_hypo2, 
                aes(x=logchange_Cherry, 
                    ymin = logchange_Strawberry-1.96*sd_logchange_Strawberry,
                    ymax = logchange_Strawberry+1.96*sd_logchange_Strawberry),
                width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(data = EC_Straw_Cher_hypo2, 
                 aes(y=logchange_Strawberry, 
                     xmin = logchange_Cherry-1.96*sd_logchange_Cherry,
                     xmax = logchange_Cherry+1.96*sd_logchange_Cherry),
                 height=0.02, size=0.2, alpha=1) + 
  geom_point(data = EC_Straw_Cher_hypo2, 
             aes(x = logchange_Cherry, y = logchange_Strawberry), 
             shape=21, size=4,  fill = "#ffffff", stroke=1.5)
PAIR_StrawChe_G29_HYPO_2


PAIR_CheCran_G29_HYPO_2<-PAIR_CheCran_G29  + 
  geom_errorbar(data = EC_Cran_Cher_hypo2, 
                aes(x=logchange_Cranberry, 
                    ymin = logchange_Cherry-1.96*sd_logchange_Cherry,
                    ymax = logchange_Cherry+1.96*sd_logchange_Cherry),
                width=0.02, size=0.2, alpha=1) + 
  geom_errorbarh(data = EC_Cran_Cher_hypo2, 
                 aes(y=logchange_Cherry, 
                     xmin = logchange_Cranberry-1.96*sd_logchange_Cranberry,
                     xmax = logchange_Cranberry+1.96*sd_logchange_Cranberry),
                 height=0.02, size=0.2, alpha=1) + 
  geom_point(data = EC_Cran_Cher_hypo2, 
             aes(x = logchange_Cranberry, y = logchange_Cherry), 
             shape=21, size=4,  fill = "#ffffff", stroke=1.5)
PAIR_CheCran_G29_HYPO_2



#legend1
legend_tradevide<- ggplot(EC_Cran_Cher_hypo2, aes(x=logchange_Cranberry, 
                                                  y=logchange_Cherry, group=Fruit_s, colour=Fruit_s)) +
  geom_point(size=1.5, position=pd, fill="white", alpha=0.6) + 
  labs(colour = "Population \nevolved on:") + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424","#3FAA96"), 
                     label=c("Cherry","Cranberry", "Strawberry")) +   
  theme_LO_sober +
  theme(legend.title = element_text(colour="black", size=10, face="bold"), 
          legend.text = element_text(colour="black", size=8))

legend_tradevide<-lemon::g_legend(legend_tradevide)

 #legend hypo 1
legend_hypo1<- ggplot(EC_Cran_Cher_hypo2, aes(x=logchange_Cranberry, 
                                                  y=logchange_Cherry, group=Fruit_s, colour=Fruit_s)) +
  geom_point(size=1.5, position=pd, fill="white", alpha=0.6) + 
  labs(colour = "Mean of population\nevolved on:") + 
  geom_point(size=2, shape=21, fill="white", stroke = 2) + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424","#3FAA96"), 
                     label=c("Cherry","Cranberry", "Strawberry")) +   
  theme_LO_sober +
  theme(legend.title = element_text(colour="black", size=10, face="bold"), 
          legend.text = element_text(colour="black", size=8))

extract_legend_hypo1<-lemon::g_legend(legend_hypo1)

 #legend2
legend_hypo2<- ggplot(EC_Cran_Cher_hypo2, aes(x=logchange_Cranberry, 
                                                  y=logchange_Cherry, group=Fruit_s, colour=Fruit_s)) +
  geom_point(size=1.5, position=pd, fill="white", alpha=0.6) + 
  labs(colour = "Population with \nthe highest fitness \non each selection fruit:") + 
  geom_point(size=2, shape=21, fill="white", stroke = 2) + 
  scale_color_manual(values=c("#BC3C6D", "#FDB424","#3FAA96"), 
                     label=c("Cherry","Cranberry", "Strawberry")) +   
  theme_LO_sober +
  theme(legend.title = element_text(colour="black", size=10, face="bold"), 
          legend.text = element_text(colour="black", size=8))
extract_legend_hypo2<-lemon::g_legend(legend_hypo2)




ERRORCROSSES_G7_HYPO1 <- cowplot::ggdraw() +
  cowplot::draw_plot(PAIR_CheCran_G29_HYPO_1+theme(legend.position = "none"), 
            x =0.00, y = 0, width = 0.25, height = 1) +
  cowplot::draw_plot(PAIR_CranStraw_G29_HYPO_1+theme(legend.position = "none"), 
            x = 0.26, y = 0, width = 0.25, height = 1) +
  cowplot::draw_plot(PAIR_StrawChe_G29_HYPO_1+theme(legend.position = "none"), 
            x = 0.52, y = 0, width = 0.25, height = 1) + 
  cowplot::draw_plot(legend_tradevide, x = 0.8, y = 0.73, width = 0.11, height = 0.1) +
  cowplot::draw_plot(extract_legend_hypo1, x = 0.83, y = 0.25, width = 0.1, height = 0.1) 
ERRORCROSSES_G7_HYPO1



ERRORCROSSES_G7_HYPO2 <- cowplot::ggdraw() +
  cowplot::draw_plot(PAIR_CheCran_G29_HYPO_2+theme(legend.position = "none"), 
            x =0.00, y = 0, width = 0.25, height = 1) +
  cowplot::draw_plot(PAIR_CranStraw_G29_HYPO_2+theme(legend.position = "none"), 
            x = 0.26, y = 0, width = 0.25, height = 1) +
  cowplot::draw_plot(PAIR_StrawChe_G29_HYPO_2+theme(legend.position = "none"), 
            x = 0.52, y = 0, width = 0.25, height = 1) + 
  cowplot::draw_plot(legend_tradevide, x = 0.78, y = 0.73, width = 0.1, height = 0.1) +
  cowplot::draw_plot(extract_legend_hypo2, x = 0.82, y = 0.25, width = 0.1, height = 0.1) 
ERRORCROSSES_G7_HYPO2








# 
# cowplot::save_plot(file =here::here("figures", "SUPMAT_Pool_Hypothesis1.pdf"),
#                    ERRORCROSSES_G7_HYPO1,
#                    base_height = 7/cm(1), base_width = 28/cm(1), dpi = 610)
# 
# 
# cowplot::save_plot(file =here::here("figures", "SUPMAT_Pool_Hypothesis2.pdf"),
#                    ERRORCROSSES_G7_HYPO2,
#                    base_height = 7/cm(1), base_width = 28/cm(1), dpi = 610)



```





