---
title: "Simulation of log fitness change"
author: "Laure Olazuacuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import data
```{r }

## Initial phenotyping
data_G0 <- loadfitnessdata(dataset = "Selection_Phenotypage_G0_G7_G8.csv", generation = "G1")

## Intemediate phenotyping
data_G7 <- loadfitnessdata(dataset = "Selection_Phenotypage_G0_G7_G8.csv", generation = "G7")

## Final phenotyping
data_G29 <- loadfitnessdata(dataset = "PERFORMANCE_Comptage_adultes_G13G14G15G16G17G18G19G20G21G22G23G24G25G26G27G28G29.csv", generation = "29")

head(data_G0)
head(data_G7)
head(data_G29)

```

# Choose the best distribution to describe the data
## Estimate parameters using negative binomial
```{r }

tapply(data_G0$Nb_adults, data_G0$Treatment, var)/tapply(data_G0$Nb_adults, data_G0$Treatment, mean)

## Fit model
mnegbin <- MASS::glm.nb(Nb_adults~1, data=data_G0)
summary(mnegbin)

## Estimation of the mean
c(observed=mean(data_G0$Nb_adults), fitted=exp(as.numeric(coef(mnegbin))))

## Estimation of the variance
c(observed=var(data_G0$Nb_adults), fitted=exp(coef(mnegbin))+(exp(coef(mnegbin))^2)/mnegbin$theta)

## Goodness of fit using fitdistrplus pacjage
fitnegbin <- fitdistrplus::fitdist(data_G0$Nb_adults, "nbinom")
plot(fitnegbin)




```

## Estimate parameters using Poisson lognormal
```{r }
data_G0$Obs <- as.factor(1:nrow(data_G0))

mpoislognormal <- lme4::glmer(Nb_adults ~ 1 + (1|Obs), data=data_G0, family="poisson")
summary(mpoislognormal)
```

## Compare Negative binomial and Poisson lognormal
```{r }

## Simulate data of the same length
x.teo.negbin <- MASS::rnegbin(n=nrow(data_G0), mu=exp(coef(mnegbin)), theta=mnegbin$theta)
x.teo.poislognormal <- unlist(simulate(mpoislognormal))

qqplot(data_G0$Nb_adults, x.teo.negbin, main="QQ-plot") ## QQ-plot
points(sort(data_G0$Nb_adults), sort(x.teo.poislognormal), pch=1, col='red')
abline(0,1)
## Add legend
legend(0, 100, legend=c("Neg. Bin.", "Pois. Lognormal"), col=c("black", "red"), pch=1, bty="n")

## Compare AIC
AIC(mnegbin, mpoislognormal)

## Cl: The fit of the Negative binomial is better


```


# Compare estimates
```{r }

## Estimate parameters for each generation and each fruit
overdispG0 <- as.data.frame(t(sapply(levels(data_G0$Treatment), estim_overdisp, data=data_G0, generation="G0")))
overdispG7 <- as.data.frame(t(sapply(levels(data_G7$Treatment), estim_overdisp, data=data_G7[data_G7$SA==1,], generation="G7")))
overdispG29 <- as.data.frame(t(sapply(levels(data_G7$Treatment), estim_overdisp, data=data_G29[data_G29$SA==1,], generation="G29")))

## Combine datasets
overdisp <- rbind(overdispG0, overdispG7, overdispG29)
names(overdisp) <- c("fruit", "generation", "fitted_mean_nb_adults", "fitted_theta", "fitted_var_nb_adults", "obsoverdisp", "fittedoverdisp")

## Sort final dataset
overdisp[order(overdisp$fruit),]
```
