---
title: "Simulation of log fitness change"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA
```{r }

#Data compo
data_compo<-read.table(file=here::here("data", "Data_compo_fruits.csv"), sep=",", header=TRUE)
rownames(data_compo) <- data_compo[,1]
data_compo$Treatment<-as.factor(data_compo$Treatment)

```


# ACP
```{r }
## Make PCA
PCA <- FactoMineR::PCA(data_compo[,-c(1,2)], graph=FALSE)

## Check eigenvalues and percentage of variance explained
eig.val <- factoextra::get_eigenvalue(PCA)
eig.val
factoextra::fviz_eig(PCA)






#pdf(file="PCA.pdf")
## Check position of individuals
Ind_plot <- factoextra::fviz(PCA, element="ind", pointsize = 3, axes = c(1, 2),
                   labelsize = 4, #change the size of the pop label
                   invisible = "quali",
                  show.legend = FALSE, col.ind = "#00AFBB",
                  pointshape = 21, 
                  fill = "#00AFBB",
                  repel = TRUE) + 
  theme_LO_sober 
Ind_plot         


## Check position of individuals
Ind_plot2 <- factoextra::fviz(PCA, element="ind", pointsize = 3, axes = c(2,3),
                   labelsize = 4, #change the size of the pop label
                   invisible = "quali",
                  show.legend = FALSE, col.ind = "#00AFBB",
                  pointshape = 21, 
                  fill = "#00AFBB",
                  repel = TRUE) + 
  theme_LO_sober 
Ind_plot2       


VARIABLES_Plot<-factoextra::fviz_pca_var(PCA, col.var = "contrib",
                                         gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                                         repel = TRUE) + theme_LO_sober
VARIABLES_Plot
VARIABLES_Plot2<-factoextra::fviz_pca_var(PCA, col.var = "contrib",axes = c(2,3),
                                         gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                                         repel = TRUE) + theme_LO_sober
VARIABLES_Plot2




factoextra::fviz_pca_ind(PCA, col.ind = "#00AFBB",
   repel = TRUE)




factoextra::fviz_pca_ind (PCA, pointsize = "cos2",
             pointshape = 21, fill = "#E7B800",
             repel = TRUE )




#Save plot 
# cowplot::save_plot(file = here::here("figures", "SUPMAT_ACP_Ind.pdf"),
#                    Ind_plot,
#                    base_height = 14/cm(1), base_width = 14/cm(1), dpi = 610)
# cowplot::save_plot(file = here::here("figures", "SUPMAT_ACP_Var.pdf"),
#                    VARIABLES_Plot,
#                    base_height = 16/cm(1), base_width = 16/cm(1), dpi = 610)
# 
# cowplot::save_plot(file = here::here("figures", "SUPMAT_ACP_Ind_axis23.pdf"),
#                    Ind_plot2,
#                    base_height = 14/cm(1), base_width = 14/cm(1), dpi = 610)
# cowplot::save_plot(file = here::here("figures", "SUPMAT_ACP_Var23.pdf"),
#                    VARIABLES_Plot2,
#                    base_height = 16/cm(1), base_width = 16/cm(1), dpi = 610)
# 



PLOT_VAR <- cowplot::ggdraw() + 
  cowplot::draw_plot(VARIABLES_Plot2 + theme(plot.title = element_blank()), 
            x = 0.01, y = 0.01, width = 1, height = 0.5) + 
  cowplot::draw_plot(VARIABLES_Plot, 
            x = 0.01, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot_label(c("A", "B"),  
                  x = c(0, 0), 
                  y = c(1, 0.5), 
                  hjust = c(0,0), 
                  vjust = c(1.5, 1.5),
                  size = 16) 
 PLOT_VAR

 cowplot::save_plot(file = here::here("figures", "SUPMAT_ACP_Var.pdf"),
                   PLOT_VAR,
                   base_height = 28/cm(1), base_width = 14/cm(1), dpi = 610)
 
 PLOT_IND <- cowplot::ggdraw() + 
  cowplot::draw_plot(Ind_plot2 + theme(plot.title = element_blank()), 
            x = 0.01, y = 0.01, width = 1, height = 0.5) + 
  cowplot::draw_plot(Ind_plot, 
            x = 0.01, y = 0.5, width = 1, height = 0.5) + 
  cowplot::draw_plot_label(c("A", "B"),  
                  x = c(0, 0), 
                  y = c(1, 0.5), 
                  hjust = c(0,0), 
                  vjust = c(1.5, 1.5),
                  size = 16) 
 PLOT_IND
 
cowplot::save_plot(file = here::here("figures", "SUPMAT_ACP_Ind.pdf"),
                   PLOT_IND,
                   base_height = 28/cm(1), base_width = 14/cm(1), dpi = 610)
```
